#!/usr/bin/env bash
# Generates packages/api-client/src/database.types.ts (IMPLEMENTATION_PLAN T-2.25;
# DATABASE_AND_RLS_PLAN §10 "Type generation") with @supabase/postgres-meta 0.99.0 in its
# PG_META_GENERATE_TYPES=typescript mode, the generator the Supabase CLI runs for `gen types`.
# Schemas: public and admin_api (the two PostgREST-exposed schemas). The output is formatted with
# the repository's prettier so `prettier --check` stays clean.
#
# Usage:
#   bash scripts/db/gen-types.sh            rebuild tier C from zero, generate, write the file
#   bash scripts/db/gen-types.sh --check    generate and fail (exit 1) when the committed file differs
#   bash scripts/db/gen-types.sh --no-migrate [--check]   reuse the current tier-C database as is
# DA_TYPEGEN_DB_URL=<libpq url> generates from another database instead of tier C (e.g. the local
# stack: postgresql://postgres:postgres@127.0.0.1:54322/postgres); --no-migrate is then implied.
set -euo pipefail
# shellcheck source=scripts/db/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
export LC_ALL=C

CHECK=0
MIGRATE=1
for arg in "$@"; do
  case "$arg" in
    --check) CHECK=1 ;;
    --no-migrate) MIGRATE=0 ;;
    *) da_die "unknown argument: $arg (usage: gen-types.sh [--check] [--no-migrate])" ;;
  esac
done

TARGET="$DA_ROOT/packages/api-client/src/database.types.ts"
SERVER="$DA_ROOT/node_modules/@supabase/postgres-meta/dist/server/server.js"
PRETTIER="$DA_ROOT/node_modules/.bin/prettier"
[[ -f "$SERVER" ]] || da_die "@supabase/postgres-meta is not installed (run pnpm install)"
[[ -x "$PRETTIER" ]] || da_die "prettier is not installed (run pnpm install)"

WORK="$(mktemp -d)"
ROLE_CREATED=0
cleanup() {
  rm -rf "$WORK"
  if ((ROLE_CREATED == 1)); then
    da_psql -c 'drop role if exists da_typegen' >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

if [[ -n "${DA_TYPEGEN_DB_URL:-}" ]]; then
  DB_URL="$DA_TYPEGEN_DB_URL"
else
  if ((MIGRATE == 1)); then
    bash "$DA_ROOT/scripts/db/tier-c.sh" --no-tests
  fi
  da_pg_resolve
  # Tier C authenticates local sockets by peer and TCP by password: a throwaway login role with a
  # random password lets the Node generator connect over 127.0.0.1; it is dropped on exit.
  password="$(od -An -tx1 -N16 /dev/urandom | tr -d ' \n')"
  da_psql -c "drop role if exists da_typegen" -c "create role da_typegen login superuser password '${password}'" >/dev/null
  ROLE_CREATED=1
  port="$(da_pg psql -X -At -d "$DA_TEST_DB" -c 'show port')"
  DB_URL="postgresql://da_typegen:${password}@127.0.0.1:${port}/${DA_TEST_DB}"
fi

da_log "generating TypeScript types for public, admin_api"
PG_META_DB_URL="$DB_URL" \
  PG_META_GENERATE_TYPES=typescript \
  PG_META_GENERATE_TYPES_INCLUDED_SCHEMAS=public,admin_api \
  PG_META_GENERATE_TYPES_DEFAULT_SCHEMA=public \
  PG_META_GENERATE_TYPES_DETECT_ONE_TO_ONE_RELATIONSHIPS=true \
  PG_META_POSTGREST_VERSION=13 \
  node --no-warnings "$SERVER" >"$WORK/raw.ts"
[[ -s "$WORK/raw.ts" ]] || da_die "the generator produced no output"

{
  printf '%s\n' '// Generated by scripts/db/gen-types.sh (@supabase/postgres-meta 0.99.0) from supabase/migrations.'
  printf '%s\n' '// Do not edit by hand: run `pnpm db:types`; CI runs `pnpm db:types:check` for drift.'
  printf '\n'
  cat "$WORK/raw.ts"
} >"$WORK/with-header.ts"
(cd "$DA_ROOT" && "$PRETTIER" --stdin-filepath packages/api-client/src/database.types.ts <"$WORK/with-header.ts" >"$WORK/formatted.ts")

if ((CHECK == 1)); then
  if [[ ! -f "$TARGET" ]] || ! diff -u --label "committed $(basename "$TARGET")" --label "generated" "$TARGET" "$WORK/formatted.ts"; then
    da_die "packages/api-client/src/database.types.ts is out of date: run pnpm db:types"
  fi
  da_log "database types are up to date"
else
  mkdir -p "$(dirname "$TARGET")"
  cp "$WORK/formatted.ts" "$TARGET"
  da_log "wrote packages/api-client/src/database.types.ts ($(wc -l <"$TARGET") lines)"
fi
