import { defineRoute } from '../route.ts';
import { Success } from './envelope.ts';
import { WidgetSnapshotV1 } from '../widget-snapshot.ts';
import { AnalyticsBody, AnalyticsResponse } from './analytics.ts';
import { AniSignalsBody, AniSignalsResponse } from './android-ni.ts';
import {
  ApprovalApproveBody,
  ApprovalApproveResponse,
  ApprovalEditBody,
  ApprovalIdParams,
  ApprovalProposeBody,
  ApprovalRejectBody,
  ApprovalViewResponse,
  DeviceExecutionBody,
  DeviceExecutionResponse,
} from './approvals.ts';
import {
  AssistantMessageBody,
  AssistantMessageReplayResponse,
  AssistantSseEvent,
  AssistantThreadBody,
  AssistantThreadParams,
  AssistantThreadResponse,
  TranscribeForm,
  TranscribeResponse,
} from './assistant.ts';
import { BootstrapResponse, EntitlementsResponse } from './bootstrap.ts';
import {
  BriefingAudioBody,
  BriefingAudioResponse,
  BriefingIdParams,
  BriefingRetryBody,
  BriefingRetryResponse,
  EveningReadyBody,
  EveningReadyResponse,
  ShareCardResponse,
} from './briefings.ts';
import {
  PurchasesSyncBody,
  PurchasesSyncResponse,
  ReferralApplyBody,
  ReferralApplyResponse,
  ReferralMeResponse,
} from './business.ts';
import {
  CaptureActionsBody,
  CaptureActionsResponse,
  CaptureAnalyzeBody,
  CaptureAnalyzeResponse,
  CaptureCreateBody,
  CaptureDiscardBody,
  CaptureIdParams,
  CaptureResponse,
  UploadUrlBody,
  UploadUrlResponse,
} from './capture.ts';
import {
  AppleExchangeBody,
  AppleExchangeResponse,
  DeviceRegisterBody,
  DeviceRegisterResponse,
  DeviceUnregisterBody,
  DeviceUnregisterResponse,
  UserTestPushBody,
  UserTestPushResponse,
} from './devices.ts';
import {
  AccountIdParams,
  DataSourcesPatch,
  DataSourcesResponse,
  DeviceSnapshotBody,
  DeviceSnapshotResponse,
  DisconnectBody,
  DisconnectResponse,
  IntegrationStartBody,
  IntegrationStartParams,
  IntegrationStartResponse,
  IntegrationUpgradeBody,
  IntegrationUpgradeResponse,
  OAuthCompleteBody,
  OAuthCompleteResponse,
  SyncBody,
  SyncResponse,
} from './integrations.ts';
import {
  DraftIdParams,
  FollowupDraftBody,
  MailOriginalQuery,
  MailOriginalResponse,
  MessageIdParams,
  ReplyAttachmentUploadBody,
  ReplyAttachmentUploadResponse,
  ReplyDraftCreateBody,
  ReplyDraftPatch,
  ReplyDraftRegenerateBody,
  ReplyDraftResponse,
  ReplyDraftSubmitBody,
  ReplyDraftSubmitResponse,
  ThreadIdParams,
  ThreadSummaryBody,
  ThreadSummaryResponse,
} from './mail.ts';
import {
  EventIdParams,
  MeetingNoteBody,
  MeetingNoteResponse,
  MeetingPostBody,
  MeetingPostResponse,
  MeetingPrepAudioBody,
  MeetingPrepAudioResponse,
  MeetingPrepBody,
  MeetingPrepResponse,
} from './meetings.ts';
import {
  FirstAnalysisBody,
  FirstAnalysisParams,
  FirstAnalysisProgress,
  FirstAnalysisResponse,
} from './onboarding.ts';
import {
  ConflictOptionsBody,
  ConflictOptionsResponse,
  ConflictParams,
  ConflictResolveBody,
  ConflictResolveResponse,
  FreeSlotsQuery,
  FreeSlotsResponse,
  PlanProposalBody,
  PlanProposalResponse,
} from './plan.ts';
import {
  DeleteAccountBody,
  DeleteAccountResponse,
  DeleteHistoryBody,
  DeleteHistoryResponse,
  ExportBody,
  ExportDownloadBody,
  ExportDownloadParams,
  ExportDownloadResponse,
  ExportResponse,
} from './privacy.ts';
import {
  ReminderCancelBody,
  ReminderCreateBody,
  ReminderIdParams,
  ReminderResponse,
  ResolveTimeBody,
  ResolveTimeResponse,
} from './reminders.ts';
import { SearchQuery, SearchResponse } from './search.ts';
import {
  FeedbackBody,
  FeedbackResponse,
  SupportTicketBody,
  SupportTicketResponse,
} from './support.ts';

/**
 * The `api` function route catalogue (`/functions/v1/api`, MASTER_PLAN §5b + the R-07/R-18/R-24
 * additions in API_CONTRACTS §8), keyed `"METHOD /path"`. The Edge router registers exactly these
 * routes with these validators; `packages/api-client` derives its typed calls from them.
 * `POST /integrations/oauth/complete` is declared before the `:accountId` routes (Hono order).
 */
export const routes = {
  // §8.1 Devices and auth
  'POST /devices/register': defineRoute({
    id: 'API-DEV-01',
    method: 'POST',
    path: '/devices/register',
    request: { body: DeviceRegisterBody },
    response: DeviceRegisterResponse,
    status: 200,
    idempotency: 'header',
  }),
  'POST /devices/unregister': defineRoute({
    id: 'API-DEV-02',
    method: 'POST',
    path: '/devices/unregister',
    request: { body: DeviceUnregisterBody },
    response: DeviceUnregisterResponse,
    status: 200,
    idempotency: 'header',
  }),
  'POST /auth/apple/exchange': defineRoute({
    id: 'API-DEV-03',
    method: 'POST',
    path: '/auth/apple/exchange',
    request: { body: AppleExchangeBody },
    response: AppleExchangeResponse,
    status: 200,
    idempotency: 'header',
  }),
  'POST /notifications/test': defineRoute({
    id: 'API-DEV-04',
    method: 'POST',
    path: '/notifications/test',
    request: { body: UserTestPushBody },
    response: UserTestPushResponse,
    status: 202,
    idempotency: 'header',
  }),
  // §8.2 Bootstrap
  'GET /me/bootstrap': defineRoute({
    id: 'API-BOOT-01',
    method: 'GET',
    path: '/me/bootstrap',
    request: {},
    response: BootstrapResponse,
    status: 200,
    idempotency: 'none',
  }),
  'GET /me/entitlements': defineRoute({
    id: 'API-BOOT-02',
    method: 'GET',
    path: '/me/entitlements',
    request: {},
    response: EntitlementsResponse,
    status: 200,
    idempotency: 'none',
  }),
  // §8.3 Integrations
  'POST /integrations/oauth/complete': defineRoute({
    id: 'API-INT-07',
    method: 'POST',
    path: '/integrations/oauth/complete',
    request: { body: OAuthCompleteBody },
    response: OAuthCompleteResponse,
    status: 200,
    idempotency: 'header',
  }),
  'POST /integrations/device-calendar/snapshot': defineRoute({
    id: 'API-INT-06',
    method: 'POST',
    path: '/integrations/device-calendar/snapshot',
    request: { body: DeviceSnapshotBody },
    response: DeviceSnapshotResponse,
    status: 202,
    idempotency: 'header',
  }),
  'POST /integrations/:provider/start': defineRoute({
    id: 'API-INT-01',
    method: 'POST',
    path: '/integrations/:provider/start',
    request: { params: IntegrationStartParams, body: IntegrationStartBody },
    response: IntegrationStartResponse,
    status: 200,
    idempotency: 'header',
  }),
  'POST /integrations/:accountId/upgrade': defineRoute({
    id: 'API-INT-02',
    method: 'POST',
    path: '/integrations/:accountId/upgrade',
    request: { params: AccountIdParams, body: IntegrationUpgradeBody },
    response: IntegrationUpgradeResponse,
    status: 200,
    idempotency: 'header',
  }),
  'POST /integrations/:accountId/disconnect': defineRoute({
    id: 'API-INT-03',
    method: 'POST',
    path: '/integrations/:accountId/disconnect',
    request: { params: AccountIdParams, body: DisconnectBody },
    response: DisconnectResponse,
    status: 200,
    idempotency: 'header',
  }),
  'POST /integrations/:accountId/sync': defineRoute({
    id: 'API-INT-04',
    method: 'POST',
    path: '/integrations/:accountId/sync',
    request: { params: AccountIdParams, body: SyncBody },
    response: SyncResponse,
    status: 202,
    idempotency: 'natural',
  }),
  'PATCH /integrations/:accountId/data-sources': defineRoute({
    id: 'API-INT-05',
    method: 'PATCH',
    path: '/integrations/:accountId/data-sources',
    request: { params: AccountIdParams, body: DataSourcesPatch },
    response: DataSourcesResponse,
    status: 200,
    idempotency: 'header',
  }),
  // §8.4 Onboarding
  'POST /onboarding/first-analysis': defineRoute({
    id: 'API-ONB-01',
    method: 'POST',
    path: '/onboarding/first-analysis',
    request: { body: FirstAnalysisBody },
    response: FirstAnalysisResponse,
    status: 202,
    idempotency: 'header',
  }),
  'GET /onboarding/first-analysis/:jobId': defineRoute({
    id: 'API-ONB-02',
    method: 'GET',
    path: '/onboarding/first-analysis/:jobId',
    request: { params: FirstAnalysisParams },
    response: FirstAnalysisProgress,
    status: 200,
    idempotency: 'none',
  }),
  // §8.5 Mail
  'GET /mail/:messageId/original': defineRoute({
    id: 'API-MAIL-01',
    method: 'GET',
    path: '/mail/:messageId/original',
    request: { params: MessageIdParams, query: MailOriginalQuery },
    response: MailOriginalResponse,
    status: 200,
    idempotency: 'none',
  }),
  'POST /mail/:messageId/reply-drafts': defineRoute({
    id: 'API-MAIL-02',
    method: 'POST',
    path: '/mail/:messageId/reply-drafts',
    request: { params: MessageIdParams, body: ReplyDraftCreateBody },
    response: ReplyDraftResponse,
    status: 201,
    idempotency: 'header',
  }),
  'POST /reply-drafts/:id/regenerate': defineRoute({
    id: 'API-MAIL-03',
    method: 'POST',
    path: '/reply-drafts/:id/regenerate',
    request: { params: DraftIdParams, body: ReplyDraftRegenerateBody },
    response: ReplyDraftResponse,
    status: 200,
    idempotency: 'header',
  }),
  'PATCH /reply-drafts/:id': defineRoute({
    id: 'API-MAIL-04',
    method: 'PATCH',
    path: '/reply-drafts/:id',
    request: { params: DraftIdParams, body: ReplyDraftPatch },
    response: ReplyDraftResponse,
    status: 200,
    idempotency: 'header',
  }),
  'POST /reply-drafts/:id/submit': defineRoute({
    id: 'API-MAIL-05',
    method: 'POST',
    path: '/reply-drafts/:id/submit',
    request: { params: DraftIdParams, body: ReplyDraftSubmitBody },
    response: ReplyDraftSubmitResponse,
    status: 201,
    idempotency: 'header',
  }),
  'POST /followups/:threadId/draft': defineRoute({
    id: 'API-MAIL-06',
    method: 'POST',
    path: '/followups/:threadId/draft',
    request: { params: ThreadIdParams, body: FollowupDraftBody },
    response: ReplyDraftResponse,
    status: 201,
    idempotency: 'header',
  }),
  'POST /mail/threads/:threadId/summary': defineRoute({
    id: 'API-MAIL-07',
    method: 'POST',
    path: '/mail/threads/:threadId/summary',
    request: { params: ThreadIdParams, body: ThreadSummaryBody },
    response: ThreadSummaryResponse,
    status: 200,
    idempotency: 'header',
  }),
  'POST /reply-drafts/:id/attachments/upload-url': defineRoute({
    id: 'API-MAIL-08',
    method: 'POST',
    path: '/reply-drafts/:id/attachments/upload-url',
    request: { params: DraftIdParams, body: ReplyAttachmentUploadBody },
    response: ReplyAttachmentUploadResponse,
    status: 201,
    idempotency: 'client_id',
  }),
  // §8.6 Approvals
  'POST /approvals': defineRoute({
    id: 'API-APR-01',
    method: 'POST',
    path: '/approvals',
    request: { body: ApprovalProposeBody },
    response: ApprovalViewResponse,
    status: 201,
    idempotency: 'header',
  }),
  'PATCH /approvals/:id': defineRoute({
    id: 'API-APR-02',
    method: 'PATCH',
    path: '/approvals/:id',
    request: { params: ApprovalIdParams, body: ApprovalEditBody },
    response: ApprovalViewResponse,
    status: 200,
    idempotency: 'header',
  }),
  'POST /approvals/:id/approve': defineRoute({
    id: 'API-APR-03',
    method: 'POST',
    path: '/approvals/:id/approve',
    request: { params: ApprovalIdParams, body: ApprovalApproveBody },
    response: ApprovalApproveResponse,
    status: 202,
    idempotency: 'header',
  }),
  'POST /approvals/:id/reject': defineRoute({
    id: 'API-APR-04',
    method: 'POST',
    path: '/approvals/:id/reject',
    request: { params: ApprovalIdParams, body: ApprovalRejectBody },
    response: ApprovalViewResponse,
    status: 200,
    idempotency: 'header',
  }),
  'POST /approvals/:id/device-execution': defineRoute({
    id: 'API-APR-05',
    method: 'POST',
    path: '/approvals/:id/device-execution',
    request: { params: ApprovalIdParams, body: DeviceExecutionBody },
    response: DeviceExecutionResponse,
    status: 200,
    idempotency: 'header',
  }),
  // §8.7 Reminders
  'POST /reminders/resolve-time': defineRoute({
    id: 'API-REM-01',
    method: 'POST',
    path: '/reminders/resolve-time',
    request: { body: ResolveTimeBody },
    response: ResolveTimeResponse,
    status: 200,
    idempotency: 'none',
  }),
  'POST /reminders': defineRoute({
    id: 'API-REM-02',
    method: 'POST',
    path: '/reminders',
    request: { body: ReminderCreateBody },
    response: ReminderResponse,
    status: 201,
    idempotency: 'client_id',
  }),
  'POST /reminders/:id/cancel': defineRoute({
    id: 'API-REM-03',
    method: 'POST',
    path: '/reminders/:id/cancel',
    request: { params: ReminderIdParams, body: ReminderCancelBody },
    response: ReminderResponse,
    status: 200,
    idempotency: 'header',
  }),
  // §8.8 Plan
  'GET /plan/free-slots': defineRoute({
    id: 'API-PLAN-01',
    method: 'GET',
    path: '/plan/free-slots',
    request: { query: FreeSlotsQuery },
    response: FreeSlotsResponse,
    status: 200,
    idempotency: 'none',
  }),
  'POST /plan/proposals': defineRoute({
    id: 'API-PLAN-02',
    method: 'POST',
    path: '/plan/proposals',
    request: { body: PlanProposalBody },
    response: PlanProposalResponse,
    status: 201,
    idempotency: 'header',
  }),
  'POST /plan/conflicts/:insightId/options': defineRoute({
    id: 'API-PLAN-03',
    method: 'POST',
    path: '/plan/conflicts/:insightId/options',
    request: { params: ConflictParams, body: ConflictOptionsBody },
    response: ConflictOptionsResponse,
    status: 200,
    idempotency: 'none',
  }),
  'POST /plan/conflicts/:insightId/resolve': defineRoute({
    id: 'API-PLAN-04',
    method: 'POST',
    path: '/plan/conflicts/:insightId/resolve',
    request: { params: ConflictParams, body: ConflictResolveBody },
    response: ConflictResolveResponse,
    status: 200,
    idempotency: 'header',
  }),
  // §8.9 Meetings
  'POST /meetings/:eventId/prep': defineRoute({
    id: 'API-MEET-01',
    method: 'POST',
    path: '/meetings/:eventId/prep',
    request: { params: EventIdParams, body: MeetingPrepBody },
    response: MeetingPrepResponse,
    status: 200,
    idempotency: 'header',
  }),
  'POST /meetings/:eventId/notes': defineRoute({
    id: 'API-MEET-02',
    method: 'POST',
    path: '/meetings/:eventId/notes',
    request: { params: EventIdParams, body: MeetingNoteBody },
    response: MeetingNoteResponse,
    status: 201,
    idempotency: 'client_id',
  }),
  'POST /meetings/:eventId/post': defineRoute({
    id: 'API-MEET-03',
    method: 'POST',
    path: '/meetings/:eventId/post',
    request: { params: EventIdParams, body: MeetingPostBody },
    response: MeetingPostResponse,
    status: 201,
    idempotency: 'client_id',
  }),
  'POST /meetings/:eventId/prep/audio': defineRoute({
    id: 'API-MEET-04',
    method: 'POST',
    path: '/meetings/:eventId/prep/audio',
    request: { params: EventIdParams, body: MeetingPrepAudioBody },
    response: MeetingPrepAudioResponse,
    status: 200,
    idempotency: 'header',
  }),
  // §8.10 Assistant
  'POST /assistant/threads': defineRoute({
    id: 'API-AST-01',
    method: 'POST',
    path: '/assistant/threads',
    request: { body: AssistantThreadBody },
    response: AssistantThreadResponse,
    status: 201,
    idempotency: 'client_id',
  }),
  'POST /assistant/threads/:id/messages': defineRoute({
    id: 'API-AST-02',
    method: 'POST',
    path: '/assistant/threads/:id/messages',
    request: { params: AssistantThreadParams, body: AssistantMessageBody },
    response: AssistantMessageReplayResponse,
    status: 200,
    idempotency: 'client_id',
    transport: 'sse',
    stream: AssistantSseEvent,
  }),
  'POST /assistant/transcribe': defineRoute({
    id: 'API-AST-03',
    method: 'POST',
    path: '/assistant/transcribe',
    request: { body: TranscribeForm },
    response: TranscribeResponse,
    status: 200,
    idempotency: 'none',
    transport: 'multipart',
  }),
  // §8.11 Search
  'GET /search': defineRoute({
    id: 'API-SRCH-01',
    method: 'GET',
    path: '/search',
    request: { query: SearchQuery },
    response: SearchResponse,
    status: 200,
    idempotency: 'none',
  }),
  // §8.12 Capture
  'POST /captures/upload-url': defineRoute({
    id: 'API-CAP-01',
    method: 'POST',
    path: '/captures/upload-url',
    request: { body: UploadUrlBody },
    response: UploadUrlResponse,
    status: 201,
    idempotency: 'client_id',
  }),
  'POST /captures': defineRoute({
    id: 'API-CAP-02',
    method: 'POST',
    path: '/captures',
    request: { body: CaptureCreateBody },
    response: CaptureResponse,
    status: 201,
    idempotency: 'client_id',
  }),
  'POST /captures/:id/analyze': defineRoute({
    id: 'API-CAP-03',
    method: 'POST',
    path: '/captures/:id/analyze',
    request: { params: CaptureIdParams, body: CaptureAnalyzeBody },
    response: CaptureAnalyzeResponse,
    status: 202,
    idempotency: 'header',
  }),
  'POST /captures/:id/actions': defineRoute({
    id: 'API-CAP-04',
    method: 'POST',
    path: '/captures/:id/actions',
    request: { params: CaptureIdParams, body: CaptureActionsBody },
    response: CaptureActionsResponse,
    status: 201,
    idempotency: 'header',
  }),
  'POST /captures/:id/discard': defineRoute({
    id: 'API-CAP-05',
    method: 'POST',
    path: '/captures/:id/discard',
    request: { params: CaptureIdParams, body: CaptureDiscardBody },
    response: CaptureResponse,
    status: 200,
    idempotency: 'header',
  }),
  // §8.13 Briefings
  'POST /briefings/:id/audio': defineRoute({
    id: 'API-BRF-01',
    method: 'POST',
    path: '/briefings/:id/audio',
    request: { params: BriefingIdParams, body: BriefingAudioBody },
    response: BriefingAudioResponse,
    status: 200,
    idempotency: 'natural',
  }),
  'POST /briefings/:id/evening-ready': defineRoute({
    id: 'API-BRF-02',
    method: 'POST',
    path: '/briefings/:id/evening-ready',
    request: { params: BriefingIdParams, body: EveningReadyBody },
    response: EveningReadyResponse,
    status: 200,
    idempotency: 'header',
  }),
  'GET /weekly/:id/share-card': defineRoute({
    id: 'API-BRF-03',
    method: 'GET',
    path: '/weekly/:id/share-card',
    request: { params: BriefingIdParams },
    response: ShareCardResponse,
    status: 200,
    idempotency: 'none',
  }),
  'POST /briefings/:id/retry': defineRoute({
    id: 'API-BRF-04',
    method: 'POST',
    path: '/briefings/:id/retry',
    request: { params: BriefingIdParams, body: BriefingRetryBody },
    response: BriefingRetryResponse,
    status: 202,
    idempotency: 'header',
  }),
  // §8.14 Business
  'POST /referrals/apply': defineRoute({
    id: 'API-BIZ-01',
    method: 'POST',
    path: '/referrals/apply',
    request: { body: ReferralApplyBody },
    response: ReferralApplyResponse,
    status: 201,
    idempotency: 'header',
  }),
  'GET /referrals/me': defineRoute({
    id: 'API-BIZ-02',
    method: 'GET',
    path: '/referrals/me',
    request: {},
    response: ReferralMeResponse,
    status: 200,
    idempotency: 'none',
  }),
  'POST /purchases/sync': defineRoute({
    id: 'API-BIZ-03',
    method: 'POST',
    path: '/purchases/sync',
    request: { body: PurchasesSyncBody },
    response: PurchasesSyncResponse,
    status: 200,
    idempotency: 'header',
  }),
  // §8.15 Privacy
  'POST /privacy/export': defineRoute({
    id: 'API-PRV-01',
    method: 'POST',
    path: '/privacy/export',
    request: { body: ExportBody },
    response: ExportResponse,
    status: 202,
    idempotency: 'header',
  }),
  'POST /privacy/delete-history': defineRoute({
    id: 'API-PRV-02',
    method: 'POST',
    path: '/privacy/delete-history',
    request: { body: DeleteHistoryBody },
    response: DeleteHistoryResponse,
    status: 202,
    idempotency: 'header',
  }),
  'POST /privacy/delete-account': defineRoute({
    id: 'API-PRV-03',
    method: 'POST',
    path: '/privacy/delete-account',
    request: { body: DeleteAccountBody },
    response: DeleteAccountResponse,
    status: 202,
    idempotency: 'header',
  }),
  'POST /privacy/export/:id/download': defineRoute({
    id: 'API-PRV-04',
    method: 'POST',
    path: '/privacy/export/:id/download',
    request: { params: ExportDownloadParams, body: ExportDownloadBody },
    response: ExportDownloadResponse,
    status: 200,
    idempotency: 'header',
  }),
  // §8.16 Support
  'POST /support/tickets': defineRoute({
    id: 'API-SUP-01',
    method: 'POST',
    path: '/support/tickets',
    request: { body: SupportTicketBody },
    response: SupportTicketResponse,
    status: 201,
    idempotency: 'header',
  }),
  'POST /feedback': defineRoute({
    id: 'API-SUP-02',
    method: 'POST',
    path: '/feedback',
    request: { body: FeedbackBody },
    response: FeedbackResponse,
    status: 201,
    idempotency: 'header',
  }),
  // §8.17 Android Notification Intelligence
  'POST /android-notifications/signals': defineRoute({
    id: 'API-ANI-01',
    method: 'POST',
    path: '/android-notifications/signals',
    request: { body: AniSignalsBody },
    response: AniSignalsResponse,
    status: 202,
    idempotency: 'header',
  }),
  // §8.18 Analytics
  'POST /analytics/events': defineRoute({
    id: 'API-ANL-01',
    method: 'POST',
    path: '/analytics/events',
    request: { body: AnalyticsBody },
    response: AnalyticsResponse,
    status: 202,
    idempotency: 'none',
  }),
  // §8.19 Widgets
  'GET /widgets/snapshot': defineRoute({
    id: 'API-WDG-01',
    method: 'GET',
    path: '/widgets/snapshot',
    request: {},
    response: Success(WidgetSnapshotV1),
    status: 200,
    idempotency: 'none',
  }),
} as const;

export type ApiRoutes = typeof routes;
export type ApiRouteKey = keyof ApiRoutes;
