/**
 * DOM icon generation for apps/web. Reads the framework-neutral Material Symbols Rounded path data
 * that `@da/ui` emits (`packages/ui/icons.data.json`, T-1.03) and writes one small React component
 * per icon the website uses to `src/components/icons/generated/`:
 *   - `fill="currentColor"`, so every icon takes its colour from the text colour (tokens only);
 *   - `aria-hidden` by default; passing `label` makes it `role="img"` with that accessible name;
 *   - `filled` switches to the FILL 1 path (active / AI-marker style).
 * Output is deterministic (sorted, no timestamps); `test/icons.test.ts` fails on drift.
 *
 * Usage: node scripts/gen-icons.ts [--check]
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const APP_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DATA_FILE = resolve(APP_DIR, '..', '..', 'packages', 'ui', 'icons.data.json');
const OUT_DIR = join(APP_DIR, 'src', 'components', 'icons', 'generated');

/** Every Material Symbol the website renders. Adding a name here and re-running is enough. */
export const WEB_ICONS = [
  'admin_panel_settings',
  'arrow_forward',
  'arrow_outward',
  'auto_awesome',
  'block',
  'calendar_month',
  'check',
  'check_circle',
  'close',
  'content_copy',
  'delete',
  'download',
  'edit_calendar',
  'error',
  'event',
  'expand_more',
  'forum',
  'groups',
  'headphones',
  'history',
  'info',
  'language',
  'lock',
  'mail',
  'mark_email_read',
  'memory',
  'menu',
  'mobile',
  'open_in_new',
  'phonelink',
  'priority_high',
  'psychology',
  'qr_code_2',
  'remove_circle',
  'schedule',
  'search',
  'shield',
  'support_agent',
  'task_alt',
  'timer_off',
  'verified_user',
  'wifi_off',
] as const;

interface IconData {
  readonly version: string;
  readonly package: string;
  readonly style: string;
  readonly icons: Readonly<
    Record<string, { readonly viewBox: string; readonly regular: string; readonly fill: string }>
  >;
}

export function componentName(name: string): string {
  return `Icon${name
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')}`;
}

function readData(): IconData {
  return JSON.parse(readFileSync(DATA_FILE, 'utf8')) as IconData;
}

function header(data: IconData): string {
  return `// Generated by apps/web scripts/gen-icons.ts from @da/ui icons.data.json (${data.package}@${data.version}, ${data.style}). Do not edit; run \`pnpm --filter @da/web generate\`.`;
}

function renderIcon(name: string, data: IconData): string {
  const icon = data.icons[name];
  if (icon === undefined) {
    throw new Error(
      `gen-icons: "${name}" is not in @da/ui icons.data.json (add it to packages/ui/icons.manifest.json)`,
    );
  }
  const same = icon.regular === icon.fill;
  const paths = same
    ? [`const PATH = '${icon.regular}';`]
    : [`const REGULAR = '${icon.regular}';`, `const FILLED = '${icon.fill}';`];
  const d = same ? 'PATH' : 'filled ? FILLED : REGULAR';
  const params = same
    ? '{ filled: _filled, ...rest }: IconProps'
    : '{ filled = false, ...rest }: IconProps';
  return [
    header(data),
    "import type { ReactNode } from 'react';",
    "import { svgProps, type IconProps } from '../props.ts';",
    '',
    ...paths,
    '',
    `/** Material Symbols Rounded \`${name}\`. */`,
    `export function ${componentName(name)}(${params}): ReactNode {`,
    '  return (',
    `    <svg viewBox="${icon.viewBox}" {...svgProps(rest)}>`,
    `      <path d={${d}} />`,
    '    </svg>',
    '  );',
    '}',
    '',
  ].join('\n');
}

function renderIndex(data: IconData): string {
  const names = [...WEB_ICONS].sort();
  return [
    header(data),
    ...names.map(
      (name) => `export { ${componentName(name)} } from './${componentName(name)}.tsx';`,
    ),
    '',
  ].join('\n');
}

/** Raw path data for image renderers (Open Graph cards, app icon) that cannot use components. */
export const IMAGE_ICONS = ['auto_awesome', 'verified_user'] as const;

function renderPaths(data: IconData): string {
  const entries = IMAGE_ICONS.map((name) => {
    const icon = data.icons[name];
    if (icon === undefined)
      throw new Error(`gen-icons: "${name}" is not in @da/ui icons.data.json`);
    return `  ${name}: { viewBox: '${icon.viewBox}', regular: '${icon.regular}', fill: '${icon.fill}' },`;
  });
  return [
    header(data),
    '/** Path data for `next/og` image renderers (Satori needs plain SVG, not components). */',
    'export const IMAGE_ICON_PATHS = {',
    ...entries,
    '} as const;',
    '',
  ].join('\n');
}

/** Every generated file keyed by its file name inside `src/components/icons/generated/`. */
export function renderAll(): Record<string, string> {
  const data = readData();
  const files: Record<string, string> = {};
  for (const name of [...WEB_ICONS].sort())
    files[`${componentName(name)}.tsx`] = renderIcon(name, data);
  files['index.ts'] = renderIndex(data);
  files['paths.ts'] = renderPaths(data);
  return files;
}

function main(): void {
  const files = renderAll();
  if (process.argv.includes('--check')) {
    const drift = Object.entries(files).filter(([file, content]) => {
      try {
        return readFileSync(join(OUT_DIR, file), 'utf8') !== content;
      } catch {
        return true;
      }
    });
    if (drift.length > 0) {
      console.error(`gen-icons: out of date: ${drift.map(([file]) => file).join(', ')}`);
      process.exit(1);
    }
    console.info('gen-icons: up to date');
    return;
  }
  mkdirSync(OUT_DIR, { recursive: true });
  for (const entry of readdirSync(OUT_DIR)) {
    if (!(entry in files)) rmSync(join(OUT_DIR, entry), { force: true });
  }
  for (const [file, content] of Object.entries(files)) writeFileSync(join(OUT_DIR, file), content);
  console.info(`gen-icons: ${String(WEB_ICONS.length)} icons written to ${OUT_DIR}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
