/**
 * Emits the platform outputs of @da/design-tokens from src/:
 *   generated/tokens.css                 CSS variables (light :root, dark overrides, system dark,
 *                                        reduced motion) + a Tailwind v4 `@theme inline` block
 *   generated/native-colors.json         light/dark colour pairs for native code
 *   generated/native/WidgetColors.swift  SwiftUI colours for the iOS WidgetKit target
 *   generated/native/DaColors.kt         Glance ColorProviders for the Android widgets
 * Output is a pure function of src/ (no timestamps, declaration order), so it is byte-identical
 * across runs. Usage: node scripts/generate.ts [--out <dir>]
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  COLOR_SCHEMES,
  SHADOW_NAMES,
  backofficeTypography,
  bezierToCss,
  duration,
  easing,
  flattenColors,
  fontStack,
  gradient,
  gradientToCss,
  opacity,
  parseColor,
  radius,
  shadow,
  shadowToCss,
  space,
  themedGradients,
  toHex,
  typography,
  webTypography,
  zIndex,
  type ColorSchemeName,
  type GradientToken,
  type TextStyleToken,
} from '../src/index.ts';

const PACKAGE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const HEADER =
  'Generated by @da/design-tokens (scripts/generate.ts) from src/. Do not edit by hand; run `pnpm --filter @da/design-tokens generate`.';

export function kebab(path: string): string {
  return path
    .replaceAll('.', '-')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase();
}

function camel(path: string): string {
  return path
    .split('.')
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');
}

function px(n: number): string {
  return n === 0 ? '0' : `${String(n)}px`;
}

function decl(name: string, value: string): string {
  return `  ${name}: ${value};`;
}

/** Declarations whose values differ between schemes. */
function schemeDeclarations(scheme: ColorSchemeName): string[] {
  const lines = flattenColors(scheme).map(([path, value]) => decl(`--da-${kebab(path)}`, value));
  for (const name of SHADOW_NAMES) {
    lines.push(decl(`--da-shadow-${kebab(name)}`, shadowToCss(shadow[scheme][name])));
  }
  const themed: Record<string, GradientToken> = { ...themedGradients(scheme) };
  for (const [name, token] of Object.entries(themed)) {
    lines.push(decl(`--da-gradient-${kebab(name)}`, gradientToCss(token)));
  }
  return lines;
}

function staticDeclarations(): string[] {
  const lines: string[] = [];
  for (const [name, token] of Object.entries(gradient)) {
    lines.push(decl(`--da-gradient-${kebab(name)}`, gradientToCss(token)));
  }
  for (const [name, value] of Object.entries(radius)) {
    lines.push(decl(`--da-radius-${kebab(name)}`, px(value)));
  }
  const steps = Object.entries(space).sort(([x], [y]) => Number(x) - Number(y));
  for (const [step, value] of steps) {
    lines.push(decl(`--da-space-${step.replace('.', '_')}`, px(value)));
  }
  for (const [name, value] of Object.entries(fontStack)) {
    lines.push(decl(`--da-font-${name}`, value));
  }
  for (const [name, curve] of Object.entries(easing)) {
    lines.push(decl(`--da-ease-${kebab(name)}`, bezierToCss(curve)));
  }
  for (const [name, ms] of Object.entries(duration)) {
    lines.push(decl(`--da-duration-${kebab(name)}`, `${String(ms)}ms`));
  }
  for (const [name, value] of Object.entries(opacity)) {
    lines.push(decl(`--da-opacity-${kebab(name)}`, String(value)));
  }
  for (const [name, value] of Object.entries(zIndex)) {
    lines.push(decl(`--da-z-${kebab(name)}`, String(value)));
  }
  return lines;
}

/** "Hareketi azalt": every duration is 0 except the 120 ms opacity transition. */
function reducedMotionDeclarations(): string[] {
  return Object.keys(duration)
    .filter((name) => name !== 'reducedOpacity')
    .map((name) => decl(`--da-duration-${kebab(name)}`, '0ms'));
}

function textDeclarations(name: string, token: TextStyleToken): string[] {
  const base = `--text-${kebab(name)}`;
  return [
    decl(base, px(token.size)),
    decl(`${base}--line-height`, px(token.lineHeight)),
    decl(`${base}--letter-spacing`, `${String(token.tracking)}em`),
    decl(`${base}--font-weight`, String(token.weight)),
  ];
}

/** Short Tailwind colour names listed in DESIGN_AUDIT §8.3, next to the full token paths. */
const TAILWIND_SHORT_COLORS: readonly (readonly [string, string])[] = [
  ['ink', 'text.primary'],
  ['ink-2', 'text.secondary'],
  ['ink-3', 'text.tertiaryStrong'],
  ['primary', 'brand.primary'],
  ['primary-soft', 'brand.soft'],
  ['on-soft', 'brand.onSoft'],
];

function themeInline(): string[] {
  const lines: string[] = [];
  for (const [path] of flattenColors('light')) {
    lines.push(decl(`--color-${kebab(path)}`, `var(--da-${kebab(path)})`));
  }
  for (const [short, path] of TAILWIND_SHORT_COLORS) {
    lines.push(decl(`--color-${short}`, `var(--da-${kebab(path)})`));
  }
  for (const name of Object.keys(fontStack)) {
    lines.push(decl(`--font-${name}`, `var(--da-font-${name})`));
  }
  for (const [name, value] of Object.entries(radius)) {
    lines.push(decl(`--radius-${kebab(name)}`, px(value)));
  }
  for (const name of SHADOW_NAMES) {
    lines.push(decl(`--shadow-${kebab(name)}`, `var(--da-shadow-${kebab(name)})`));
  }
  for (const name of Object.keys(easing)) {
    lines.push(decl(`--ease-${kebab(name)}`, `var(--da-ease-${kebab(name)})`));
  }
  for (const [name, token] of Object.entries(typography))
    lines.push(...textDeclarations(name, token));
  for (const [name, token] of Object.entries(backofficeTypography)) {
    lines.push(...textDeclarations(name, token));
  }
  // Mobile-first: `text-web-display md:text-web-display-md lg:text-web-display-lg`.
  for (const [name, tokens] of Object.entries(webTypography)) {
    const list: readonly TextStyleToken[] = tokens;
    const suffixes = list.length === 1 ? [''] : ['-lg', '-md', ''];
    list.forEach((token, index) => {
      lines.push(...textDeclarations(`${name}${suffixes[index] ?? ''}`, token));
    });
  }
  return lines;
}

function block(selector: string, lines: string[], indent = ''): string {
  const body = lines.map((l) => `${indent}${l}`).join('\n');
  return `${indent}${selector} {\n${body}\n${indent}}`;
}

export function renderCss(): string {
  const dark = [decl('color-scheme', 'dark'), ...schemeDeclarations('dark')];
  return [
    `/* ${HEADER} */`,
    '',
    block(':root', [
      decl('color-scheme', 'light'),
      ...schemeDeclarations('light'),
      ...staticDeclarations(),
    ]),
    '',
    block('[data-theme="dark"]', dark),
    '',
    '@media (prefers-color-scheme: dark) {',
    block(':root:not([data-theme="light"])', dark, '  '),
    '}',
    '',
    '@media (prefers-reduced-motion: reduce) {',
    block(':root', reducedMotionDeclarations(), '  '),
    '}',
    '',
    block('@theme inline', themeInline()),
    '',
  ].join('\n');
}

interface NativeColor {
  readonly light: string;
  readonly dark: string;
}

function nativeColors(): [string, NativeColor][] {
  const dark = new Map(flattenColors('dark'));
  return flattenColors('light').map(([path, lightValue]) => {
    const darkValue = dark.get(path);
    if (darkValue === undefined) throw new Error(`Dark scheme is missing ${path}`);
    return [path, { light: toHex(parseColor(lightValue)), dark: toHex(parseColor(darkValue)) }];
  });
}

export function renderNativeJson(): string {
  const colors: Record<string, NativeColor> = {};
  for (const [path, value] of nativeColors()) colors[path] = value;
  const doc = {
    generatedBy: '@da/design-tokens scripts/generate.ts',
    format: '#RRGGBB, or #RRGGBBAA when translucent (alpha last, 8-bit)',
    schemes: COLOR_SCHEMES,
    colors,
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

export function renderSwift(): string {
  const rgba = (hex: string): string => {
    const c = parseColor(hex);
    const alphaByte = Math.round(c.a * 255);
    return `rgba(${String(c.r)}, ${String(c.g)}, ${String(c.b)}, ${String(alphaByte)})`;
  };
  const members = nativeColors().map(
    ([path, value]) =>
      `  /// \`${path}\`\n  public static let ${camel(path)} = dynamic(${rgba(value.light)}, ${rgba(value.dark)})`,
  );
  return [
    `// ${HEADER}`,
    '// Task T-8.25 wires this file into apps/mobile/targets/widget/Generated/.',
    'import SwiftUI',
    'import UIKit',
    '',
    '/// sRGB colour from 8-bit channels (alpha 0–255, the same bytes as native-colors.json).',
    'private func rgba(_ r: Int, _ g: Int, _ b: Int, _ a: Int) -> UIColor {',
    '  UIColor(',
    '    red: CGFloat(r) / 255, green: CGFloat(g) / 255, blue: CGFloat(b) / 255,',
    '    alpha: CGFloat(a) / 255)',
    '}',
    '',
    'private func dynamic(_ light: UIColor, _ dark: UIColor) -> Color {',
    '  Color(uiColor: UIColor { traits in traits.userInterfaceStyle == .dark ? dark : light })',
    '}',
    '',
    '/// Dijital Asistan semantic colours; each resolves to its light or dark value.',
    'public enum WidgetColors {',
    members.join('\n'),
    '}',
    '',
  ].join('\n');
}

export function renderKotlin(): string {
  const argb = (hex: string): string => {
    const c = parseColor(hex);
    const byte = (n: number): string => Math.round(n).toString(16).padStart(2, '0').toUpperCase();
    return `Color(0x${byte(c.a * 255)}${byte(c.r)}${byte(c.g)}${byte(c.b)})`;
  };
  const members = nativeColors().map(
    ([path, value]) =>
      `    /** \`${path}\` */\n    val ${camel(path)} = ColorProvider(day = ${argb(value.light)}, night = ${argb(value.dark)})`,
  );
  return [
    `// ${HEADER}`,
    '// Task T-8.25 wires this file into',
    '// apps/mobile/modules/da-widgets/android/src/main/java/expo/modules/dawidgets/generated/.',
    'package expo.modules.dawidgets.generated',
    '',
    'import androidx.compose.ui.graphics.Color',
    'import androidx.glance.color.ColorProvider',
    '',
    '/** Dijital Asistan semantic colours as Glance day/night colour providers. */',
    'object DaColors {',
    members.join('\n'),
    '}',
    '',
  ].join('\n');
}

/** Every generated file, keyed by its path relative to the package directory. */
export function renderAll(): Record<string, string> {
  return {
    'generated/tokens.css': renderCss(),
    'generated/native-colors.json': renderNativeJson(),
    'generated/native/WidgetColors.swift': renderSwift(),
    'generated/native/DaColors.kt': renderKotlin(),
  };
}

function main(): void {
  const idx = process.argv.indexOf('--out');
  const outDir = idx > -1 ? resolve(process.argv[idx + 1] ?? '.') : PACKAGE_DIR;
  const files = renderAll();
  for (const [rel, content] of Object.entries(files)) {
    const target = join(outDir, rel);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content);
  }
  console.info(`design-tokens: wrote ${String(Object.keys(files).length)} files to ${outDir}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
