import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['test/**/*.test.ts'],
    environment: 'node',
    // TEST_PLAN §16 / T-12.04: `pnpm test` enforces 85% lines and functions, 75% branches.
    // `database.types.ts` is generated by `pnpm db:types` and excluded.
    coverage: {
      enabled: true,
      provider: 'v8',
      include: ['src/**/*.ts'],
      exclude: ['src/database.types.ts'],
      reporter: ['text-summary'],
      thresholds: { lines: 85, branches: 75, functions: 85 },
    },
  },
});
