/**
 * Material Symbols Rounded for React Native. `<Icon name filled size color accessibilityLabel />`
 * renders one of the manifest icons (icons.manifest.json); the per-icon components are
 * generated by `scripts/gen-icons.ts`.
 */
export { Icon, type IconProps } from './Icon.tsx';
export * from './generated/index.ts';
export type { IconGlyph, IconGlyphProps } from './types.ts';
