/**
 * Backoffice icon codegen (DESIGN_AUDIT §2.12.2 "Backoffice" + UI glyphs). Reads the framework-neutral
 * Material Symbols Rounded data emitted by `@da/ui` (`packages/ui/icons.data.json`) and writes
 * `src/generated/icons.ts` with only the glyphs the backoffice renders, so the client bundle never
 * carries the whole icon set. Run with `node scripts/gen-icons.ts` (`pnpm --filter @da/backoffice
 * generate`); `--check` exits 1 when the committed file is stale.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const APP = join(HERE, '..');
const SOURCE = join(APP, '..', '..', 'packages', 'ui', 'icons.data.json');
const TARGET = join(APP, 'src', 'generated', 'icons.ts');

/** Every glyph the backoffice uses, sorted. Navigation icons follow DESIGN_AUDIT §2.12.2. */
export const BACKOFFICE_ICONS = [
  'admin_panel_settings',
  'arrow_back',
  'arrow_downward',
  'arrow_forward',
  'arrow_upward',
  'campaign',
  'check',
  'check_circle',
  'chevron_right',
  'close',
  'content_copy',
  'dark_mode',
  'download',
  'error',
  'expand_more',
  'feedback',
  'filter_alt',
  'group',
  'history_edu',
  'hub',
  'info',
  'key',
  'light_mode',
  'lock',
  'logout',
  'menu',
  'monitor_heart',
  'more_vert',
  'notifications',
  'policy',
  'redeem',
  'refresh',
  'schedule',
  'search',
  'search_off',
  'settings',
  'shield',
  'smart_toy',
  'space_dashboard',
  'support_agent',
  'sync_alt',
  'terminal',
  'toggle_on',
  'trending_down',
  'trending_up',
  'view_column',
  'visibility',
  'visibility_off',
  'wb_twilight',
  'wifi_off',
  'workspace_premium',
] as const;

interface IconData {
  source: string;
  viewBox: string;
  regular: string;
  fill?: string;
}

export function render(data: { version: string; icons: Record<string, IconData> }): string {
  const missing = BACKOFFICE_ICONS.filter((name) => data.icons[name] === undefined);
  if (missing.length > 0) {
    throw new Error(`Icons missing from packages/ui/icons.data.json: ${missing.join(', ')}`);
  }
  const entries = BACKOFFICE_ICONS.map((name) => {
    const icon = data.icons[name];
    if (icon === undefined) throw new Error(`Icon missing: ${name}`);
    const fill = icon.fill === undefined ? '' : `, fill: ${JSON.stringify(icon.fill)}`;
    return `  ${name}: { viewBox: ${JSON.stringify(icon.viewBox)}, regular: ${JSON.stringify(icon.regular)}${fill} },`;
  });
  return [
    `// Generated by apps/backoffice/scripts/gen-icons.ts from @material-symbols/svg-400@${data.version} (rounded) via packages/ui/icons.data.json. Do not edit.`,
    '',
    'export interface IconGlyph {',
    '  readonly viewBox: string;',
    '  readonly regular: string;',
    '  readonly fill?: string;',
    '}',
    '',
    'export const ICONS = {',
    ...entries,
    '} as const satisfies Record<string, IconGlyph>;',
    '',
    'export type IconName = keyof typeof ICONS;',
    '',
  ].join('\n');
}

function main(): void {
  const data = JSON.parse(readFileSync(SOURCE, 'utf8')) as {
    version: string;
    icons: Record<string, IconData>;
  };
  const output = render(data);
  if (process.argv.includes('--check')) {
    const current = existsSync(TARGET) ? readFileSync(TARGET, 'utf8') : '';
    if (current !== output) {
      console.error(
        'src/generated/icons.ts is stale: run `pnpm --filter @da/backoffice generate`.',
      );
      process.exit(1);
    }
    return;
  }
  mkdirSync(dirname(TARGET), { recursive: true });
  writeFileSync(TARGET, output);
  console.info(`icons: wrote ${String(BACKOFFICE_ICONS.length)} glyphs to src/generated/icons.ts`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
