import type { z } from 'zod';
import type { HttpMethod, RouteRequest } from '../route.ts';
import * as ai from './ai.ts';
import * as brf from './briefings.ts';
import {
  EmptyAdminBody,
  IdParams,
  RangeQuery,
  RevealResponse,
  UserIdParams,
  type AdminAccess,
  type AdminRouteContract,
} from './common.ts';
import * as dash from './dashboard.ts';
import * as intg from './integrations.ts';
import * as jobs from './jobs.ts';
import * as ops from './privacy-ops.ts';
import * as product from './product.ts';
import * as prompts from './prompts.ts';
import * as session from './session.ts';
import * as subs from './subscriptions.ts';
import * as support from './support.ts';
import * as sys from './system.ts';
import * as users from './users.ts';
import type { AuditAction } from './audit-actions.ts';

export type { AdminRouteContract } from './common.ts';

function read(
  id: string,
  path: string,
  access: AdminAccess,
  request: RouteRequest,
  response: z.ZodType,
): AdminRouteContract {
  return { id, method: 'GET', path, access, request, response, status: 200, idempotency: 'none' };
}

function write(
  id: string,
  method: Exclude<HttpMethod, 'GET'>,
  path: string,
  access: AdminAccess,
  request: RouteRequest,
  response: z.ZodType,
  options: { status?: 200 | 201 | 202; audit?: AuditAction } = {},
): AdminRouteContract {
  return {
    id,
    method,
    path,
    access,
    request,
    response,
    status: options.status ?? 200,
    idempotency: 'header',
    ...(options.audit === undefined ? {} : { audit: options.audit }),
  };
}

const own: AdminAccess = { require: 'own' };
const anyAdmin: AdminAccess = { require: 'any_admin' };
const bff: AdminAccess = { require: 'bff' };
const aal1: AdminAccess = { require: 'aal1' };
const perm = (
  require: AdminAccess['require'],
  extra: Omit<AdminAccess, 'require'> = {},
): AdminAccess => ({ require, ...extra });
const stepUp = (require: AdminAccess['require']): AdminAccess => ({ require, step_up: true });
const flagWrite: AdminAccess = { require: 'flags.write', or: ['flags.write_ai'] };

const idBody = (body: z.ZodType): RouteRequest => ({ params: IdParams, body });

/**
 * The `admin-api` route catalogue (`/functions/v1/admin-api`, API_CONTRACTS §12.3, ADM-00…ADM-21),
 * keyed `"METHOD /path"`. Every route declares exactly one primary permission (or an own-account /
 * BFF class); `also` / `or` carry the documented module combinations. Literal paths such as
 * `/users/lookup`, `/jobs/stats`, `/audit/verify-chain` are registered before their `/:id` siblings.
 */
export const adminRoutes = {
  // ADM-00 · Session and preferences
  'POST /session/start': write(
    'ADM-00',
    'POST',
    '/session/start',
    anyAdmin,
    { body: session.SessionStartBody },
    session.SessionStartResponse,
    { audit: 'admin.login' },
  ),
  'POST /session/heartbeat': write(
    'ADM-00',
    'POST',
    '/session/heartbeat',
    anyAdmin,
    { body: session.SessionHeartbeatBody },
    session.SessionHeartbeatResponse,
  ),
  'GET /me': read(
    'ADM-00',
    '/me',
    own,
    { headers: session.AdminMeHeaders },
    session.AdminMeResponse,
  ),
  'GET /me/sessions': read('ADM-00', '/me/sessions', own, {}, session.AdminSessionsResponse),
  'POST /session/logout': write(
    'ADM-00',
    'POST',
    '/session/logout',
    own,
    { body: session.SessionLogoutBody },
    session.SessionEndedResponse,
    { audit: 'admin.logout' },
  ),
  'POST /session/logout-all': write(
    'ADM-00',
    'POST',
    '/session/logout-all',
    own,
    { body: session.SessionLogoutAllBody },
    session.SessionEndedResponse,
    { audit: 'admin.logout_all' },
  ),
  'GET /preferences': read('ADM-00', '/preferences', own, {}, session.AdminPreferencesResponse),
  'PATCH /preferences': write(
    'ADM-00',
    'PATCH',
    '/preferences',
    own,
    { body: session.AdminPreferencesPatch },
    session.AdminPreferencesResponse,
  ),
  'POST /auth/preflight': write(
    'ADM-00',
    'POST',
    '/auth/preflight',
    bff,
    { body: session.AuthPreflightBody },
    session.AuthPreflightResponse,
  ),
  'POST /auth/attempt': write(
    'ADM-00',
    'POST',
    '/auth/attempt',
    bff,
    { body: session.AuthAttemptBody },
    session.AuthAttemptResponse,
    { audit: 'admin.login_failed' },
  ),
  'GET /auth/status': read('ADM-00', '/auth/status', aal1, {}, session.AuthStatusResponse),
  'POST /auth/invite/redeem': write(
    'ADM-00',
    'POST',
    '/auth/invite/redeem',
    bff,
    { body: session.InviteRedeemBody },
    session.InviteRedeemResponse,
    { audit: 'admin.invite_redeemed' },
  ),
  'POST /auth/recovery-code/redeem': write(
    'ADM-00',
    'POST',
    '/auth/recovery-code/redeem',
    aal1,
    { body: session.RecoveryCodeRedeemBody },
    session.RecoveryCodeRedeemResponse,
    { audit: 'admin.mfa_recovery_used' },
  ),
  'POST /me/recovery-codes': write(
    'ADM-00',
    'POST',
    '/me/recovery-codes',
    stepUp('own'),
    { body: session.RecoveryCodesBody },
    session.RecoveryCodesResponse,
    { status: 201, audit: 'admin.recovery_codes_regenerated' },
  ),
  'POST /me/mfa-factors': write(
    'ADM-00',
    'POST',
    '/me/mfa-factors',
    own,
    { body: session.MfaFactorConfirmBody },
    session.MfaFactorResponse,
    { status: 201, audit: 'admin.mfa_factor_added' },
  ),
  'DELETE /me/mfa-factors/:factorId': write(
    'ADM-00',
    'DELETE',
    '/me/mfa-factors/:factorId',
    stepUp('own'),
    { params: session.MfaFactorParams, body: session.MfaFactorRemoveBody },
    session.MfaFactorResponse,
    { audit: 'admin.mfa_factor_removed' },
  ),
  'POST /session/step-up': write(
    'ADM-00',
    'POST',
    '/session/step-up',
    own,
    { body: session.StepUpBody },
    session.StepUpResponse,
    { audit: 'admin.step_up' },
  ),

  // ADM-01 · Dashboard
  'GET /dashboard/metrics': read(
    'ADM-01',
    '/dashboard/metrics',
    perm('dashboard.read'),
    { query: dash.DashboardMetricsQuery },
    dash.DashboardMetricsResponse,
  ),
  'GET /dashboard/charts': read(
    'ADM-01',
    '/dashboard/charts',
    perm('dashboard.read'),
    { query: dash.DashboardChartsQuery },
    dash.DashboardChartsResponse,
  ),
  'GET /metrics/ops': read(
    'ADM-01',
    '/metrics/ops',
    perm('metrics.ops.read'),
    { query: RangeQuery },
    dash.MetricsGroupsResponse,
  ),
  'GET /metrics/product': read(
    'ADM-01',
    '/metrics/product',
    perm('metrics.product.read'),
    { query: RangeQuery },
    dash.MetricsGroupsResponse,
  ),
  'GET /security-events': read(
    'ADM-01',
    '/security-events',
    perm('admins.manage'),
    { query: RangeQuery },
    dash.SecurityEventsResponse,
  ),

  // ADM-02 · Users and user actions
  'GET /users': read(
    'ADM-02',
    '/users',
    perm('users.read'),
    { query: users.UsersListQuery },
    users.UsersListResponse,
  ),
  'POST /users/lookup': write(
    'ADM-02',
    'POST',
    '/users/lookup',
    perm('users.read'),
    { body: users.UserLookupBody },
    users.UserLookupResponse,
  ),
  'GET /users/:id': read(
    'ADM-02',
    '/users/:id',
    perm('users.read'),
    { params: UserIdParams },
    users.UserOverviewResponse,
  ),
  'GET /users/:id/integrations': read(
    'ADM-02',
    '/users/:id/integrations',
    perm('users.read', { also: ['integrations.read'] }),
    { params: UserIdParams },
    users.UserIntegrationsResponse,
  ),
  'GET /users/:id/briefings': read(
    'ADM-02',
    '/users/:id/briefings',
    perm('users.read', { also: ['briefings.read'] }),
    { params: UserIdParams, query: users.UserBriefingsQuery },
    users.UserBriefingsResponse,
  ),
  'GET /users/:id/usage': read(
    'ADM-02',
    '/users/:id/usage',
    perm('users.read'),
    { params: UserIdParams, query: users.UserUsageQuery },
    users.UserUsageResponse,
  ),
  'GET /users/:id/subscription': read(
    'ADM-02',
    '/users/:id/subscription',
    perm('users.read', { also: ['subscriptions.read'] }),
    { params: UserIdParams, query: users.UserSubscriptionQuery },
    users.UserSubscriptionResponse,
  ),
  'GET /users/:id/referrals': read(
    'ADM-02',
    '/users/:id/referrals',
    perm('users.read', { also: ['referrals.read'] }),
    { params: UserIdParams, query: users.UserReferralsQuery },
    users.UserReferralsResponse,
  ),
  'GET /users/:id/support': read(
    'ADM-02',
    '/users/:id/support',
    perm('users.read', { also: ['support.read'] }),
    { params: UserIdParams, query: users.UserSupportQuery },
    users.UserSupportResponse,
  ),
  'GET /users/:id/audit': read(
    'ADM-02',
    '/users/:id/audit',
    perm('users.read', { also: ['audit.read'] }),
    { params: UserIdParams, query: ops.AuditListQuery },
    ops.AuditListResponse,
  ),
  'GET /users/:id/devices': read(
    'ADM-02',
    '/users/:id/devices',
    perm('users.read', { also: ['notifications.read'] }),
    { params: UserIdParams },
    users.UserDevicesResponse,
  ),
  'POST /users/:id/reveal': write(
    'ADM-02',
    'POST',
    '/users/:id/reveal',
    perm('users.pii.reveal'),
    idBody(users.UserRevealBody),
    RevealResponse,
    { audit: 'user.pii_revealed' },
  ),
  'POST /users/:id/force-sync': write(
    'ADM-02',
    'POST',
    '/users/:id/force-sync',
    perm('users.force_sync'),
    idBody(users.UserForceSyncBody),
    users.UserForceSyncResponse,
    { status: 202, audit: 'user.force_sync' },
  ),
  'POST /users/:id/disable': write(
    'ADM-02',
    'POST',
    '/users/:id/disable',
    stepUp('users.disable'),
    idBody(users.UserDisableBody),
    users.UserStateResponse,
    { audit: 'user.disabled' },
  ),
  'POST /users/:id/restore': write(
    'ADM-02',
    'POST',
    '/users/:id/restore',
    stepUp('users.disable'),
    idBody(users.UserRestoreBody),
    users.UserStateResponse,
    { audit: 'user.restored' },
  ),
  'POST /users/:id/entitlement-grants': write(
    'ADM-02',
    'POST',
    '/users/:id/entitlement-grants',
    perm('entitlements.grant', { or: ['entitlements.grant_limited'] }),
    idBody(users.EntitlementGrantBody),
    users.EntitlementGrantResponse,
    { status: 201, audit: 'entitlement.granted' },
  ),
  'POST /users/:id/entitlement-grants/:grantId/revoke': write(
    'ADM-02',
    'POST',
    '/users/:id/entitlement-grants/:grantId/revoke',
    perm('entitlements.revoke'),
    { params: users.GrantParams, body: users.GrantRevokeBody },
    users.EntitlementGrantResponse,
    { audit: 'entitlement.revoked' },
  ),
  'POST /users/:id/integrations/:accountId/disconnect': write(
    'ADM-02',
    'POST',
    '/users/:id/integrations/:accountId/disconnect',
    stepUp('integrations.disconnect'),
    { params: users.UserIntegrationParams, body: users.AdminDisconnectBody },
    users.AdminDisconnectResponse,
    { audit: 'integration.disconnected' },
  ),
  'POST /users/:id/internal': write(
    'ADM-02',
    'POST',
    '/users/:id/internal',
    perm('users.mark_internal'),
    idBody(users.UserInternalBody),
    users.UserInternalResponse,
    { audit: 'user.marked_internal' },
  ),

  // ADM-03 · Support and Support Access
  'GET /support/tickets': read(
    'ADM-03',
    '/support/tickets',
    perm('support.read'),
    { query: support.TicketsListQuery },
    support.TicketsListResponse,
  ),
  'GET /support/tickets/:id': read(
    'ADM-03',
    '/support/tickets/:id',
    perm('support.read'),
    { params: IdParams },
    support.TicketDetailResponse,
  ),
  'PATCH /support/tickets/:id': write(
    'ADM-03',
    'PATCH',
    '/support/tickets/:id',
    perm('support.write'),
    idBody(support.TicketPatchBody),
    support.TicketResponse,
    { audit: 'ticket.updated' },
  ),
  'POST /support/tickets/:id/notes': write(
    'ADM-03',
    'POST',
    '/support/tickets/:id/notes',
    perm('support.write'),
    idBody(support.TicketNoteBody),
    support.TicketNoteResponse,
    { status: 201, audit: 'ticket.note_added' },
  ),
  'POST /support/tickets/:id/reply': write(
    'ADM-03',
    'POST',
    '/support/tickets/:id/reply',
    perm('support.write'),
    idBody(support.TicketNoteBody),
    support.TicketReplyResponse,
    { status: 202, audit: 'ticket.reply_sent' },
  ),
  'POST /support-access/grants': write(
    'ADM-03',
    'POST',
    '/support-access/grants',
    stepUp('support.access'),
    { body: support.SupportAccessGrantBody },
    support.SupportAccessGrantResponse,
    { status: 201, audit: 'support_access.granted' },
  ),
  'POST /support-access/grants/:id/revoke': write(
    'ADM-03',
    'POST',
    '/support-access/grants/:id/revoke',
    perm('support.access'),
    idBody(support.SupportAccessRevokeBody),
    support.SupportAccessGrantResponse,
    { audit: 'support_access.revoked' },
  ),
  'GET /support-access/grants/:id/content/:scope': read(
    'ADM-03',
    '/support-access/grants/:id/content/:scope',
    perm('support.access'),
    { params: support.SupportContentParams, query: support.SupportContentQuery },
    support.SupportContentResponse,
  ),

  // ADM-04 · Integrations
  'GET /integrations': read(
    'ADM-04',
    '/integrations',
    perm('integrations.read'),
    { query: intg.IntegrationsListQuery },
    intg.IntegrationsListResponse,
  ),
  'GET /integrations/summary': read(
    'ADM-04',
    '/integrations/summary',
    perm('integrations.read', { or: ['metrics.ops.read'] }),
    { query: intg.IntegrationsSummaryQuery },
    intg.IntegrationsSummaryResponse,
  ),
  'GET /integrations/:accountId': read(
    'ADM-04',
    '/integrations/:accountId',
    perm('integrations.read'),
    { params: intg.AccountParams },
    intg.IntegrationDetailResponse,
  ),
  'POST /integrations/:accountId/force-sync': write(
    'ADM-04',
    'POST',
    '/integrations/:accountId/force-sync',
    perm('users.force_sync'),
    { params: intg.AccountParams, body: intg.IntegrationForceSyncBody },
    intg.IntegrationJobsResponse,
    { status: 202, audit: 'user.force_sync' },
  ),
  'POST /integrations/:accountId/renew-watch': write(
    'ADM-04',
    'POST',
    '/integrations/:accountId/renew-watch',
    perm('integrations.renew_watch'),
    { params: intg.AccountParams, body: intg.IntegrationRenewWatchBody },
    intg.IntegrationJobsResponse,
    { status: 202, audit: 'integration.watch_renew_requested' },
  ),

  // ADM-05 · Sync and jobs
  'GET /jobs': read(
    'ADM-05',
    '/jobs',
    perm('jobs.read'),
    { query: jobs.JobsListQuery },
    jobs.JobsListResponse,
  ),
  'GET /jobs/stats': read(
    'ADM-05',
    '/jobs/stats',
    perm('jobs.read'),
    { query: jobs.JobsStatsQuery },
    jobs.JobsStatsResponse,
  ),
  'POST /jobs/retry-bulk': write(
    'ADM-05',
    'POST',
    '/jobs/retry-bulk',
    perm('jobs.retry'),
    { body: jobs.JobsBulkRetryBody },
    jobs.JobsBulkRetryResponse,
    { audit: 'job.bulk_retried' },
  ),
  'GET /jobs/:id': read(
    'ADM-05',
    '/jobs/:id',
    perm('jobs.read'),
    { params: IdParams },
    jobs.JobDetailResponse,
  ),
  'GET /correlation/:id': read(
    'ADM-05',
    '/correlation/:id',
    perm('jobs.read'),
    { params: jobs.CorrelationParams },
    jobs.CorrelationTraceResponse,
  ),
  'POST /jobs/:id/retry': write(
    'ADM-05',
    'POST',
    '/jobs/:id/retry',
    perm('jobs.retry'),
    idBody(jobs.JobRetryBody),
    jobs.JobMutationResponse,
    { audit: 'job.retried' },
  ),
  'POST /jobs/:id/cancel': write(
    'ADM-05',
    'POST',
    '/jobs/:id/cancel',
    perm('jobs.cancel'),
    idBody(jobs.JobCancelBody),
    jobs.JobMutationResponse,
    { audit: 'job.cancelled' },
  ),

  // ADM-06 · Briefings
  'GET /briefings/metrics': read(
    'ADM-06',
    '/briefings/metrics',
    perm('briefings.read'),
    { query: brf.BriefingsMetricsQuery },
    brf.BriefingsMetricsResponse,
  ),
  'GET /briefings': read(
    'ADM-06',
    '/briefings',
    perm('briefings.read'),
    { query: brf.BriefingsListQuery },
    brf.BriefingsListResponse,
  ),
  'POST /briefings/:id/regenerate': write(
    'ADM-06',
    'POST',
    '/briefings/:id/regenerate',
    perm('briefings.regenerate'),
    idBody(brf.BriefingRegenerateBody),
    brf.BriefingRegenerateResponse,
    { status: 202, audit: 'briefing.regenerated' },
  ),

  // ADM-07 · Notifications
  'GET /notifications/metrics': read(
    'ADM-07',
    '/notifications/metrics',
    perm('notifications.read'),
    { query: brf.NotificationsMetricsQuery },
    brf.NotificationsMetricsResponse,
  ),
  'GET /notifications': read(
    'ADM-07',
    '/notifications',
    perm('notifications.read'),
    { query: brf.NotificationsListQuery },
    brf.NotificationsListResponse,
  ),
  'POST /notifications/test-push': write(
    'ADM-07',
    'POST',
    '/notifications/test-push',
    perm('push.test'),
    { body: brf.AdminTestPushBody },
    brf.AdminTestPushResponse,
    { status: 202, audit: 'push.test_sent' },
  ),
  'GET /notifications/test-push/preview': read(
    'ADM-07',
    '/notifications/test-push/preview',
    perm('push.test'),
    { query: brf.AdminTestPushPreviewQuery },
    brf.AdminTestPushPreviewResponse,
  ),

  // ADM-08 · AI Operations and Model Config
  'GET /ai/metrics': read(
    'ADM-08',
    '/ai/metrics',
    perm('ai.read', { or: ['metrics.ai.read'] }),
    { query: ai.AiMetricsQuery },
    ai.AiMetricsResponse,
  ),
  'GET /ai/metrics/series': read(
    'ADM-08',
    '/ai/metrics/series',
    perm('ai.read', { or: ['metrics.ai.read'] }),
    { query: ai.AiMetricsSeriesQuery },
    ai.AiMetricsSeriesResponse,
  ),
  'GET /ai/requests': read(
    'ADM-08',
    '/ai/requests',
    perm('ai.read'),
    { query: ai.AiRequestsQuery },
    ai.AiRequestsResponse,
  ),
  'GET /ai/models': read('ADM-08', '/ai/models', perm('ai.read'), {}, ai.AiModelsResponse),
  'PATCH /ai/models/:profile/:feature': write(
    'ADM-08',
    'PATCH',
    '/ai/models/:profile/:feature',
    perm('ai.models.write'),
    { params: ai.ModelConfigParams, body: ai.ModelConfigPatch },
    ai.ModelConfigResponse,
    { audit: 'ai_model_config.updated' },
  ),
  'POST /ai/models/:profile/:feature/test': write(
    'ADM-08',
    'POST',
    '/ai/models/:profile/:feature/test',
    perm('ai.models.write'),
    { params: ai.ModelConfigParams, body: ai.ModelProbeBody },
    ai.ModelProbeResponse,
    { audit: 'ai_model_config.tested' },
  ),
  'PATCH /ai/routing-profile': write(
    'ADM-08',
    'PATCH',
    '/ai/routing-profile',
    perm('ai.models.write'),
    { body: ai.RoutingProfileBody },
    ai.RoutingProfileResponse,
    { audit: 'ai_routing_profile.changed' },
  ),

  // ADM-09 · Prompt management
  'GET /ai/prompts': read(
    'ADM-09',
    '/ai/prompts',
    perm('prompts.read'),
    {},
    prompts.PromptsListResponse,
  ),
  'GET /ai/prompts/:key': read(
    'ADM-09',
    '/ai/prompts/:key',
    perm('prompts.read'),
    { params: prompts.PromptKeyParams },
    prompts.PromptVersionsResponse,
  ),
  'GET /ai/prompts/:key/diff': read(
    'ADM-09',
    '/ai/prompts/:key/diff',
    perm('prompts.read'),
    { params: prompts.PromptKeyParams, query: prompts.PromptDiffQuery },
    prompts.PromptDiffResponse,
  ),
  'GET /ai/prompts/:key/versions/:v': read(
    'ADM-09',
    '/ai/prompts/:key/versions/:v',
    perm('prompts.read'),
    { params: prompts.PromptVersionParams },
    prompts.PromptVersionDetailResponse,
  ),
  'POST /ai/prompts/:key/versions': write(
    'ADM-09',
    'POST',
    '/ai/prompts/:key/versions',
    perm('prompts.write'),
    { params: prompts.PromptKeyParams, body: prompts.PromptDraftBody },
    prompts.PromptVersionResponse,
    { status: 201, audit: 'prompt.draft_created' },
  ),
  'PATCH /ai/prompts/:key/versions/:v': write(
    'ADM-09',
    'PATCH',
    '/ai/prompts/:key/versions/:v',
    perm('prompts.write'),
    { params: prompts.PromptVersionParams, body: prompts.PromptDraftPatch },
    prompts.PromptVersionResponse,
    { audit: 'prompt.draft_updated' },
  ),
  'POST /ai/prompts/:key/versions/:v/test': write(
    'ADM-09',
    'POST',
    '/ai/prompts/:key/versions/:v/test',
    perm('prompts.write'),
    { params: prompts.PromptVersionParams, body: prompts.PromptTestBody },
    prompts.PromptTestResponse,
  ),
  'POST /ai/prompts/:key/versions/:v/activate': write(
    'ADM-09',
    'POST',
    '/ai/prompts/:key/versions/:v/activate',
    perm('prompts.activate'),
    { params: prompts.PromptVersionParams, body: prompts.PromptActivateBody },
    prompts.PromptVersionResponse,
    { audit: 'prompt.activated' },
  ),
  'POST /ai/prompts/:key/rollback': write(
    'ADM-09',
    'POST',
    '/ai/prompts/:key/rollback',
    perm('prompts.activate'),
    { params: prompts.PromptKeyParams, body: prompts.PromptRollbackBody },
    prompts.PromptVersionResponse,
    { audit: 'prompt.rolled_back' },
  ),
  'POST /ai/prompts/:key/versions/:v/archive': write(
    'ADM-09',
    'POST',
    '/ai/prompts/:key/versions/:v/archive',
    perm('prompts.activate'),
    { params: prompts.PromptVersionParams, body: prompts.PromptArchiveBody },
    prompts.PromptVersionResponse,
    { audit: 'prompt.archived' },
  ),

  // ADM-10 · AI Feedback
  'GET /ai/feedback/aggregates': read(
    'ADM-10',
    '/ai/feedback/aggregates',
    perm('ai_feedback.read'),
    { query: ai.AiFeedbackAggregatesQuery },
    ai.AiFeedbackAggregatesResponse,
  ),
  'GET /ai/feedback': read(
    'ADM-10',
    '/ai/feedback',
    perm('ai_feedback.read'),
    { query: ai.AiFeedbackListQuery },
    ai.AiFeedbackListResponse,
  ),
  'POST /ai/feedback/:id/reveal': write(
    'ADM-10',
    'POST',
    '/ai/feedback/:id/reveal',
    perm('ai_feedback.reveal'),
    idBody(ai.AiFeedbackRevealBody),
    ai.AiFeedbackRevealResponse,
    { audit: 'ai_feedback.comment_revealed' },
  ),

  // ADM-11 · Subscriptions
  'GET /subscriptions/metrics': read(
    'ADM-11',
    '/subscriptions/metrics',
    perm('subscriptions.read'),
    { query: subs.SubscriptionsMetricsQuery },
    subs.SubscriptionsMetricsResponse,
  ),
  'GET /subscriptions': read(
    'ADM-11',
    '/subscriptions',
    perm('subscriptions.read'),
    { query: subs.SubscriptionsListQuery },
    subs.SubscriptionsListResponse,
  ),
  'GET /subscriptions/events': read(
    'ADM-11',
    '/subscriptions/events',
    perm('billing_events.read'),
    { query: subs.BillingEventsQuery },
    subs.BillingEventsResponse,
  ),
  'GET /subscriptions/trial-stream': read(
    'ADM-11',
    '/subscriptions/trial-stream',
    perm('subscriptions.read'),
    { query: subs.TrialStreamQuery },
    subs.TrialStreamResponse,
  ),
  'GET /subscriptions/events/:id': read(
    'ADM-11',
    '/subscriptions/events/:id',
    perm('billing_events.read'),
    { params: subs.BillingEventParams },
    subs.BillingEventDetailResponse,
  ),
  'GET /entitlement-grants': read(
    'ADM-11',
    '/entitlement-grants',
    perm('subscriptions.read'),
    { query: subs.EntitlementGrantsListQuery },
    subs.EntitlementGrantsListResponse,
  ),
  'POST /subscriptions/:userId/sync': write(
    'ADM-11',
    'POST',
    '/subscriptions/:userId/sync',
    perm('subscriptions.resync'),
    { params: subs.SubscriptionUserParams, body: subs.SubscriptionResyncBody },
    subs.SubscriptionResyncResponse,
    { status: 202, audit: 'subscription.resync_requested' },
  ),

  // ADM-12 · Referrals
  'GET /referrals/metrics': read(
    'ADM-12',
    '/referrals/metrics',
    perm('referrals.read'),
    { query: subs.ReferralsMetricsQuery },
    subs.ReferralsMetricsResponse,
  ),
  'GET /referrals': read(
    'ADM-12',
    '/referrals',
    perm('referrals.read'),
    { query: subs.ReferralsListQuery },
    subs.ReferralsListResponse,
  ),
  'POST /referrals/:id/approve': write(
    'ADM-12',
    'POST',
    '/referrals/:id/approve',
    perm('referrals.review'),
    idBody(subs.ReferralReviewBody),
    subs.ReferralReviewResponse,
    { audit: 'referral.approved' },
  ),
  'POST /referrals/:id/reject': write(
    'ADM-12',
    'POST',
    '/referrals/:id/reject',
    perm('referrals.review'),
    idBody(subs.ReferralReviewBody),
    subs.ReferralReviewResponse,
    { audit: 'referral.rejected' },
  ),

  // ADM-13 · Feedback
  'GET /feedback': read(
    'ADM-13',
    '/feedback',
    perm('feedback.read'),
    { query: product.FeedbackListQuery },
    product.FeedbackListResponse,
  ),
  'GET /feedback/summary': read(
    'ADM-13',
    '/feedback/summary',
    perm('feedback.read'),
    { query: product.FeedbackSummaryQuery },
    product.FeedbackSummaryResponse,
  ),
  'PATCH /feedback/:id': write(
    'ADM-13',
    'PATCH',
    '/feedback/:id',
    perm('feedback.write'),
    idBody(product.FeedbackPatchBody),
    product.FeedbackResponse,
    { audit: 'feedback.updated' },
  ),
  'POST /feedback/:id/reveal': write(
    'ADM-13',
    'POST',
    '/feedback/:id/reveal',
    perm('users.pii.reveal'),
    idBody(product.FeedbackRevealBody),
    product.FeedbackRevealResponse,
    { audit: 'feedback.revealed' },
  ),

  // ADM-14 · Feature flags
  'GET /flags': read(
    'ADM-14',
    '/flags',
    perm('flags.read'),
    { query: product.FlagsListQuery },
    product.FlagsListResponse,
  ),
  'GET /flags/:key': read(
    'ADM-14',
    '/flags/:key',
    perm('flags.read'),
    { params: product.FlagParams },
    product.FlagDetailResponse,
  ),
  'GET /flags/:key/evaluate': read(
    'ADM-14',
    '/flags/:key/evaluate',
    perm('flags.read'),
    { params: product.FlagParams, query: product.FlagEvaluateQuery },
    product.FlagEvaluateResponse,
  ),
  'POST /flags': write(
    'ADM-14',
    'POST',
    '/flags',
    flagWrite,
    { body: product.FlagCreateBody },
    product.FlagResponse,
    { status: 201, audit: 'flag.created' },
  ),
  'PATCH /flags/:key': write(
    'ADM-14',
    'PATCH',
    '/flags/:key',
    flagWrite,
    { params: product.FlagParams, body: product.FlagPatchBody },
    product.FlagResponse,
    { audit: 'flag.updated' },
  ),
  'POST /flags/:key/kill': write(
    'ADM-14',
    'POST',
    '/flags/:key/kill',
    flagWrite,
    { params: product.FlagParams, body: product.FlagKillBody },
    product.FlagResponse,
    { audit: 'flag.kill_switch_on' },
  ),
  'POST /flags/:key/archive': write(
    'ADM-14',
    'POST',
    '/flags/:key/archive',
    flagWrite,
    { params: product.FlagParams, body: product.FlagArchiveBody },
    product.FlagResponse,
    { audit: 'flag.archived' },
  ),
  'POST /flags/:key/overrides': write(
    'ADM-14',
    'POST',
    '/flags/:key/overrides',
    flagWrite,
    { params: product.FlagParams, body: product.FlagOverrideBody },
    product.FlagOverrideResponse,
    { status: 201, audit: 'flag.override_added' },
  ),
  'DELETE /flags/:key/overrides/:userId': write(
    'ADM-14',
    'DELETE',
    '/flags/:key/overrides/:userId',
    flagWrite,
    { params: product.FlagOverrideParams, body: EmptyAdminBody },
    product.FlagOverrideResponse,
    { audit: 'flag.override_removed' },
  ),

  // ADM-15 · Announcements
  'GET /announcements': read(
    'ADM-15',
    '/announcements',
    perm('announcements.read'),
    { query: product.AnnouncementsListQuery },
    product.AnnouncementsListResponse,
  ),
  'POST /announcements/audience-estimate': write(
    'ADM-15',
    'POST',
    '/announcements/audience-estimate',
    perm('announcements.read'),
    { body: product.AudienceEstimateBody },
    product.AudienceEstimateResponse,
  ),
  'GET /announcements/:id': read(
    'ADM-15',
    '/announcements/:id',
    perm('announcements.read'),
    { params: IdParams },
    product.AnnouncementDetailResponse,
  ),
  'POST /announcements': write(
    'ADM-15',
    'POST',
    '/announcements',
    perm('announcements.write'),
    { body: product.AnnouncementBody },
    product.AnnouncementResponse,
    { status: 201, audit: 'announcement.created' },
  ),
  'PATCH /announcements/:id': write(
    'ADM-15',
    'PATCH',
    '/announcements/:id',
    perm('announcements.write'),
    idBody(product.AnnouncementPatchBody),
    product.AnnouncementResponse,
    { audit: 'announcement.updated' },
  ),
  'POST /announcements/:id/preview': write(
    'ADM-15',
    'POST',
    '/announcements/:id/preview',
    perm('announcements.read'),
    idBody(product.AnnouncementPreviewBody),
    product.AnnouncementPreviewResponse,
  ),
  'POST /announcements/:id/schedule': write(
    'ADM-15',
    'POST',
    '/announcements/:id/schedule',
    perm('announcements.write'),
    idBody(product.AnnouncementScheduleBody),
    product.AnnouncementResponse,
    { audit: 'announcement.scheduled' },
  ),
  'POST /announcements/:id/cancel': write(
    'ADM-15',
    'POST',
    '/announcements/:id/cancel',
    perm('announcements.write'),
    idBody(product.AnnouncementCancelBody),
    product.AnnouncementResponse,
    { audit: 'announcement.cancelled' },
  ),

  // ADM-16 · Data requests
  'GET /data-requests': read(
    'ADM-16',
    '/data-requests',
    perm('data_requests.read'),
    { query: ops.DataRequestsListQuery },
    ops.DataRequestsListResponse,
  ),
  'POST /data-requests/export/:id/regenerate': write(
    'ADM-16',
    'POST',
    '/data-requests/export/:id/regenerate',
    perm('data_requests.manage'),
    { params: ops.ExportRegenerateParams, body: ops.ExportRegenerateBody },
    ops.ExportRegenerateResponse,
    { status: 202, audit: 'data_request.export_regenerated' },
  ),
  'GET /data-requests/:kind/:id': read(
    'ADM-16',
    '/data-requests/:kind/:id',
    perm('data_requests.read'),
    { params: ops.DataRequestParams },
    ops.DataRequestDetailResponse,
  ),
  'POST /data-requests/:kind/:id/retry': write(
    'ADM-16',
    'POST',
    '/data-requests/:kind/:id/retry',
    perm('data_requests.manage'),
    { params: ops.DataRequestParams, body: ops.DataRequestRetryBody },
    ops.DataRequestRetryResponse,
    { status: 202, audit: 'data_request.retried' },
  ),

  // ADM-17 · Audit logs (read-only; no update or delete route exists)
  'GET /audit': read(
    'ADM-17',
    '/audit',
    perm('audit.read'),
    { query: ops.AuditListQuery },
    ops.AuditListResponse,
  ),
  'GET /audit/verify-chain': read(
    'ADM-17',
    '/audit/verify-chain',
    perm('audit.read'),
    { query: ops.AuditVerifyQuery },
    ops.AuditVerifyResponse,
  ),
  'GET /audit/:id': read(
    'ADM-17',
    '/audit/:id',
    perm('audit.read'),
    { params: IdParams },
    ops.AuditDetailResponse,
  ),

  // ADM-18 · System Health and observability
  'GET /health/summary': read(
    'ADM-18',
    '/health/summary',
    perm('health.read'),
    {},
    sys.HealthSummaryResponse,
  ),
  'GET /health/history': read(
    'ADM-18',
    '/health/history',
    perm('health.read'),
    { query: sys.HealthHistoryQuery },
    sys.HealthHistoryResponse,
  ),
  'POST /health/run': write(
    'ADM-18',
    'POST',
    '/health/run',
    perm('health.run'),
    { body: sys.HealthRunBody },
    sys.HealthRunResponse,
    { audit: 'health.run_requested' },
  ),
  'GET /health/app-versions': read(
    'ADM-18',
    '/health/app-versions',
    perm('health.read'),
    { query: sys.AppVersionsQuery },
    sys.AppVersionsResponse,
  ),
  'GET /health/cron': read(
    'ADM-18',
    '/health/cron',
    perm('health.read'),
    {},
    sys.CronHealthResponse,
  ),

  // ADM-19 · Admin users
  'GET /admins': read('ADM-19', '/admins', perm('admins.read'), {}, sys.AdminUsersResponse),
  'POST /admins/invite': write(
    'ADM-19',
    'POST',
    '/admins/invite',
    stepUp('admins.manage'),
    { body: sys.AdminInviteBody },
    sys.AdminUserResponse,
    { status: 201, audit: 'admin.invited' },
  ),
  'PATCH /admins/:id': write(
    'ADM-19',
    'PATCH',
    '/admins/:id',
    stepUp('admins.manage'),
    idBody(sys.AdminRoleBody),
    sys.AdminUserResponse,
    { audit: 'admin.role_changed' },
  ),
  'POST /admins/:id/disable': write(
    'ADM-19',
    'POST',
    '/admins/:id/disable',
    stepUp('admins.manage'),
    idBody(sys.AdminStatusBody),
    sys.AdminUserResponse,
    { audit: 'admin.disabled' },
  ),
  'POST /admins/:id/enable': write(
    'ADM-19',
    'POST',
    '/admins/:id/enable',
    stepUp('admins.manage'),
    idBody(sys.AdminStatusBody),
    sys.AdminUserResponse,
    { audit: 'admin.enabled' },
  ),
  'POST /admins/:id/revoke-sessions': write(
    'ADM-19',
    'POST',
    '/admins/:id/revoke-sessions',
    stepUp('admins.manage'),
    idBody(sys.AdminReasonBody),
    sys.AdminSessionsRevokedResponse,
    { audit: 'admin.sessions_revoked' },
  ),
  'POST /admins/:id/resend-invite': write(
    'ADM-19',
    'POST',
    '/admins/:id/resend-invite',
    stepUp('admins.manage'),
    idBody(sys.AdminReasonBody),
    sys.AdminUserResponse,
    { audit: 'admin.invite_resent' },
  ),
  'POST /admins/:id/reset-mfa': write(
    'ADM-19',
    'POST',
    '/admins/:id/reset-mfa',
    stepUp('admins.manage'),
    idBody(sys.AdminResetMfaBody),
    sys.AdminUserResponse,
    { audit: 'admin.mfa_reset' },
  ),
  'POST /admins/:id/unlock': write(
    'ADM-19',
    'POST',
    '/admins/:id/unlock',
    stepUp('admins.manage'),
    idBody(sys.AdminReasonBody),
    sys.AdminUserResponse,
    { audit: 'admin.unlocked' },
  ),

  // ADM-20 · Settings
  'GET /settings': read('ADM-20', '/settings', anyAdmin, {}, sys.SettingsResponse),
  'PATCH /settings/plan-limits': write(
    'ADM-20',
    'PATCH',
    '/settings/plan-limits',
    stepUp('settings.system.write'),
    { body: sys.PlanLimitPatchBody },
    sys.SettingChangedResponse,
    { audit: 'plan_limits.updated' },
  ),
  'PATCH /settings/config/:key': write(
    'ADM-20',
    'PATCH',
    '/settings/config/:key',
    stepUp('settings.system.write'),
    { params: sys.ConfigParams, body: sys.ConfigPatchBody },
    sys.SettingChangedResponse,
    { audit: 'settings.system_updated' },
  ),

  // ADM-21 · Global search and command palette
  'GET /search': read(
    'ADM-21',
    '/search',
    perm('search.global'),
    { query: sys.AdminSearchQuery },
    sys.AdminSearchResponse,
  ),
} as const satisfies Record<string, AdminRouteContract>;

export type AdminRoutes = typeof adminRoutes;
export type AdminRouteKey = keyof AdminRoutes;
