/**
 * Generates the Deno configs of the Edge Functions from `supabase/functions/import_map.base.json`
 * (IMPLEMENTATION_PLAN T-3.01):
 * - `supabase/functions/<fn>/deno.json` for each of the nine functions (deployed with the function);
 * - `supabase/functions/deno.json`, the workspace config used by `deno check|lint|test`.
 *
 * Usage: node scripts/functions/sync-import-maps.ts [--check]
 * `--check` writes nothing and exits 1 when a generated file drifts from the base map.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';

const HERE = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(HERE, '..', '..');
export const FUNCTIONS_DIR = join(REPO_ROOT, 'supabase', 'functions');

/** The canonical function set (MASTER_PLAN ADR-04). */
export const FUNCTION_NAMES = [
  'api',
  'oauth',
  'webhooks-google',
  'webhooks-microsoft',
  'webhooks-revenuecat',
  'worker',
  'admin-api',
  'public-api',
  'health',
] as const;

interface BaseMap {
  imports: Record<string, string>;
}

function isLocalTarget(target: string): boolean {
  return target.startsWith('./') || target.startsWith('../');
}

/** Rewrites a local target written relative to a function directory for another directory. */
export function rebaseTarget(target: string, fromDir: string, toDir: string): string {
  if (!isLocalTarget(target)) return target;
  const absolute = resolve(fromDir, target);
  let rel = relative(toDir, absolute).split('\\').join('/');
  if (!rel.startsWith('.')) rel = `./${rel}`;
  if (target.endsWith('/') && !rel.endsWith('/')) rel = `${rel}/`;
  return rel;
}

export function readBaseMap(): BaseMap {
  const raw = JSON.parse(
    readFileSync(join(FUNCTIONS_DIR, 'import_map.base.json'), 'utf8'),
  ) as Partial<BaseMap>;
  if (typeof raw.imports !== 'object') throw new Error('import_map.base.json: missing "imports"');
  return { imports: raw.imports };
}

/** Deno lint rules shared by every function (the service-client allow-list is a separate guard). */
const LINT = {
  rules: {
    tags: ['recommended'],
    include: ['eqeqeq', 'no-console', 'no-throw-literal'],
  },
};

export function buildConfigs(base: BaseMap): Map<string, unknown> {
  const out = new Map<string, unknown>();
  const sampleFnDir = join(FUNCTIONS_DIR, FUNCTION_NAMES[0]);
  for (const fn of FUNCTION_NAMES) {
    const fnDir = join(FUNCTIONS_DIR, fn);
    const imports: Record<string, string> = {};
    for (const [key, target] of Object.entries(base.imports)) {
      imports[key] = rebaseTarget(target, sampleFnDir, fnDir);
    }
    out.set(join(fnDir, 'deno.json'), {
      $comment: 'Generated by scripts/functions/sync-import-maps.ts from ../import_map.base.json.',
      imports,
      nodeModulesDir: 'none',
      lock: false,
    });
  }
  const workspaceImports: Record<string, string> = {};
  for (const [key, target] of Object.entries(base.imports)) {
    workspaceImports[key] = rebaseTarget(target, sampleFnDir, FUNCTIONS_DIR);
  }
  out.set(join(FUNCTIONS_DIR, 'deno.json'), {
    $comment:
      'Generated by scripts/functions/sync-import-maps.ts from import_map.base.json. Workspace config for deno check, lint and test.',
    imports: workspaceImports,
    nodeModulesDir: 'none',
    lock: false,
    lint: LINT,
  });
  return out;
}

async function render(path: string, value: unknown): Promise<string> {
  const options = (await prettier.resolveConfig(path)) ?? {};
  return prettier.format(JSON.stringify(value, null, 2), { ...options, filepath: path });
}

export async function syncImportMaps(check: boolean): Promise<string[]> {
  const drift: string[] = [];
  for (const [path, value] of buildConfigs(readBaseMap())) {
    const next = await render(path, value);
    const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
    if (current === next) continue;
    drift.push(relative(REPO_ROOT, path));
    if (!check) writeFileSync(path, next);
  }
  return drift;
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const drift = await syncImportMaps(check);
  if (check && drift.length > 0) {
    console.error(`functions:imports drift in:\n  ${drift.join('\n  ')}`);
    console.error('Run `pnpm functions:imports` and commit the result.');
    process.exit(1);
  }
  console.info(
    check
      ? 'functions:imports: no drift'
      : `functions:imports: ${drift.length === 0 ? 'up to date' : `wrote ${drift.join(', ')}`}`,
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
