/**
 * Mobile brand assets (DESIGN_AUDIT §8.6): the PRIMARY brand mark is the filled `auto_awesome`
 * glyph (Material Symbols `star_shine`, taken from the `@da/ui` icon data) in white on the
 * `brand.primary` indigo, sized like the design's tiles (glyph em box = 56 % of an icon, 30/56 of
 * the 56-pt tile with radius 18).
 *
 * Step 1 writes `apps/mobile/assets/src/*.svg` from the design tokens and the glyph (committed, so
 * a review sees the exact source). Step 2 rasterises each SVG with headless Chromium, crops the
 * canvas out of the screenshot and re-encodes it (RGB for the opaque icon, RGBA otherwise) into
 * `apps/mobile/assets/*.png`, then verifies size, opacity and white-on-transparent pixels.
 *
 * Usage:
 *   node scripts/mobile/render-assets.ts           write SVGs and render PNGs
 *   node scripts/mobile/render-assets.ts --check   fail if the committed SVGs or PNG shapes drifted
 * Chromium: `CHROME_PATH`, else the Playwright build under /opt/pw-browsers, else `chromium` on PATH.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { crc32, deflateSync, inflateSync } from 'node:zlib';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const ASSET_DIR = join(ROOT, 'apps', 'mobile', 'assets');
const SVG_DIR = join(ASSET_DIR, 'src');

interface IconData {
  icons: Record<string, { source: string; viewBox: string; fill: string } | undefined>;
}
interface NativeColors {
  colors: Record<string, { light: string; dark: string } | undefined>;
}

export interface AssetSpec {
  /** File stem shared by `assets/src/<name>.svg` and `assets/<name>.png`. */
  readonly name: string;
  /** Square canvas size in pixels. */
  readonly size: number;
  /** Glyph em box as a fraction of the canvas. */
  readonly glyph: number;
  /** Indigo backdrop with a corner radius as a fraction of the canvas; absent = transparent. */
  readonly tile?: { readonly radius: number };
  /** Pixel rule checked after rendering. */
  readonly pixels: 'opaque' | 'white-on-transparent' | 'any';
}

/**
 * - icon: iOS/marketing icon, full-bleed and opaque (the OS applies the mask).
 * - adaptive-icon: Android foreground and monochrome layer; the glyph keeps the icon's 56 % of the
 *   visible 72 dp inside the 108 dp canvas, well inside the 66 dp safe zone.
 * - splash: the 56/r18 brand tile shown by expo-splash-screen at 96 pt on `bg` (light and dark).
 * - notification-icon: Android status-bar icon, alpha-only white glyph at 24 dp × 4.
 */
export const ASSET_SPECS: readonly AssetSpec[] = [
  { name: 'icon', size: 1024, glyph: 0.56, tile: { radius: 0 }, pixels: 'opaque' },
  { name: 'adaptive-icon', size: 1024, glyph: (0.56 * 72) / 108, pixels: 'white-on-transparent' },
  { name: 'splash', size: 512, glyph: 30 / 56, tile: { radius: 18 / 56 }, pixels: 'any' },
  { name: 'notification-icon', size: 96, glyph: 1, pixels: 'white-on-transparent' },
];

function readJson(path: string): unknown {
  return JSON.parse(readFileSync(join(ROOT, path), 'utf8'));
}

function requireValue<T>(value: T | undefined, what: string): T {
  if (value === undefined) throw new Error(`render-assets: missing ${what}`);
  return value;
}

const fmt = (n: number) => String(Math.round(n * 100) / 100);

/** Builds the SVG source of one asset from the tokens and the brand glyph. */
export function buildSvg(spec: AssetSpec): string {
  const icons = readJson('packages/ui/icons.data.json') as IconData;
  const colors = readJson('packages/design-tokens/generated/native-colors.json') as NativeColors;
  const glyph = requireValue(icons.icons.auto_awesome, 'auto_awesome glyph in @da/ui icon data');
  const brand = requireValue(colors.colors['brand.primary'], 'brand.primary colour').light;
  const onBrand = requireValue(colors.colors['text.onPrimary'], 'text.onPrimary colour').light;

  const { size } = spec;
  const box = size * spec.glyph;
  const offset = (size - box) / 2;
  const lines = [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">`,
    `  <!-- Generated by scripts/mobile/render-assets.ts from @da/design-tokens and the @da/ui ${glyph.source} glyph. -->`,
  ];
  if (spec.tile) {
    const r = fmt(size * spec.tile.radius);
    lines.push(`  <rect width="${size}" height="${size}" rx="${r}" ry="${r}" fill="${brand}"/>`);
  }
  lines.push(
    `  <svg x="${fmt(offset)}" y="${fmt(offset)}" width="${fmt(box)}" height="${fmt(box)}" viewBox="${glyph.viewBox}">`,
    `    <path fill="${onBrand}" d="${glyph.fill}"/>`,
    '  </svg>',
    '</svg>',
    '',
  );
  return lines.join('\n');
}

// ── PNG codec (8-bit RGBA / RGB, non-interlaced: what Chromium writes) ──────────────────────────
export interface DecodedPng {
  width: number;
  height: number;
  channels: number;
  pixels: Uint8Array;
}

export function decodePng(buffer: Buffer): DecodedPng {
  if (buffer.readUInt32BE(12) !== 0x49484452) throw new Error('not a PNG (missing IHDR)');
  const width = buffer.readUInt32BE(16);
  const height = buffer.readUInt32BE(20);
  const bitDepth = buffer[24];
  const colorType = buffer[25];
  const interlace = buffer[28];
  const channels = colorType === 6 ? 4 : colorType === 2 ? 3 : 0;
  if (bitDepth !== 8 || channels === 0 || interlace !== 0) {
    throw new Error(`unsupported PNG layout (depth ${bitDepth}, type ${colorType})`);
  }
  const chunks: Buffer[] = [];
  for (let at = 8; at < buffer.length;) {
    const length = buffer.readUInt32BE(at);
    const type = buffer.toString('latin1', at + 4, at + 8);
    if (type === 'IDAT') chunks.push(buffer.subarray(at + 8, at + 8 + length));
    at += 12 + length;
  }
  const raw = inflateSync(Buffer.concat(chunks));
  const stride = width * channels;
  const pixels = new Uint8Array(height * stride);
  for (let y = 0; y < height; y++) {
    const filter = raw[y * (stride + 1)] ?? 0;
    for (let x = 0; x < stride; x++) {
      const value = raw[y * (stride + 1) + 1 + x] ?? 0;
      const left = x >= channels ? (pixels[y * stride + x - channels] ?? 0) : 0;
      const up = y > 0 ? (pixels[(y - 1) * stride + x] ?? 0) : 0;
      const upLeft = x >= channels && y > 0 ? (pixels[(y - 1) * stride + x - channels] ?? 0) : 0;
      let predictor = 0;
      if (filter === 1) predictor = left;
      else if (filter === 2) predictor = up;
      else if (filter === 3) predictor = Math.floor((left + up) / 2);
      else if (filter === 4) {
        const p = left + up - upLeft;
        const pa = Math.abs(p - left);
        const pb = Math.abs(p - up);
        const pc = Math.abs(p - upLeft);
        predictor = pa <= pb && pa <= pc ? left : pb <= pc ? up : upLeft;
      }
      pixels[y * stride + x] = (value + predictor) & 0xff;
    }
  }
  return { width, height, channels, pixels };
}

function chunk(type: string, data: Buffer): Buffer {
  const head = Buffer.alloc(8);
  head.writeUInt32BE(data.length, 0);
  head.write(type, 4, 'latin1');
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([head.subarray(4), data])) >>> 0, 0);
  return Buffer.concat([head, data, crc]);
}

/** Encodes pixels with filter 0 and maximum deflate, so the output depends on the pixels only. */
export function encodePng(png: DecodedPng): Buffer {
  const stride = png.width * png.channels;
  const raw = Buffer.alloc(png.height * (stride + 1));
  for (let y = 0; y < png.height; y++) {
    raw[y * (stride + 1)] = 0;
    raw.set(png.pixels.subarray(y * stride, (y + 1) * stride), y * (stride + 1) + 1);
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(png.width, 0);
  ihdr.writeUInt32BE(png.height, 4);
  ihdr[8] = 8;
  ihdr[9] = png.channels === 4 ? 6 : 2;
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/** Copies the top-left `size`² square, optionally dropping the alpha channel. */
export function crop(png: DecodedPng, size: number, channels: 3 | 4): DecodedPng {
  if (png.width < size || png.height < size) {
    throw new Error(`screenshot ${png.width}×${png.height} is smaller than ${size}²`);
  }
  const pixels = new Uint8Array(size * size * channels);
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const from = (y * png.width + x) * png.channels;
      const to = (y * size + x) * channels;
      for (let c = 0; c < channels; c++) pixels[to + c] = png.pixels[from + c] ?? 0;
    }
  }
  return { width: size, height: size, channels, pixels };
}

/** Returns a list of problems with a rendered PNG (empty when it matches its spec). */
export function inspectPng(spec: AssetSpec, png: DecodedPng): string[] {
  const problems: string[] = [];
  if (png.width !== spec.size || png.height !== spec.size) {
    problems.push(`${spec.name}.png is ${png.width}×${png.height}, expected ${spec.size}²`);
  }
  let inked = 0;
  for (let i = 0; i < png.width * png.height; i++) {
    const base = i * png.channels;
    const alpha = png.channels === 4 ? (png.pixels[base + 3] ?? 0) : 255;
    const [r, g, b] = [png.pixels[base] ?? 0, png.pixels[base + 1] ?? 0, png.pixels[base + 2] ?? 0];
    if (alpha > 0) inked++;
    if (spec.pixels === 'opaque' && alpha !== 255) {
      problems.push(`${spec.name}.png has a transparent pixel`);
      break;
    }
    if (spec.pixels === 'white-on-transparent' && alpha > 16 && Math.min(r, g, b) < 240) {
      problems.push(`${spec.name}.png has a non-white pixel`);
      break;
    }
  }
  if (inked === 0) problems.push(`${spec.name}.png is empty`);
  return problems;
}

function findChrome(): string {
  const candidates = [
    process.env.CHROME_PATH,
    '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
    '/opt/pw-browsers/chromium/chrome-linux/chrome',
  ];
  for (const candidate of candidates) if (candidate && existsSync(candidate)) return candidate;
  return 'chromium';
}

/**
 * Headless Chromium draws the SVG at the top-left of a larger window (the headless viewport is
 * shorter than `--window-size`, and very small windows are clamped), so the canvas is cropped out.
 */
function render(chrome: string, svgPath: string, pngPath: string, spec: AssetSpec): void {
  const profile = mkdtempSync(join(tmpdir(), 'da-mobile-assets-'));
  const shot = join(profile, 'shot.png');
  const window = Math.max(spec.size, 512) + 256;
  try {
    execFileSync(
      chrome,
      [
        '--headless=new',
        '--no-sandbox',
        '--disable-gpu',
        '--hide-scrollbars',
        '--no-first-run',
        '--force-device-scale-factor=1',
        '--default-background-color=00000000',
        `--user-data-dir=${profile}`,
        `--window-size=${window},${window}`,
        `--screenshot=${shot}`,
        pathToFileURL(svgPath).href,
      ],
      { stdio: 'pipe' },
    );
    const channels = spec.pixels === 'opaque' ? 3 : 4;
    writeFileSync(pngPath, encodePng(crop(decodePng(readFileSync(shot)), spec.size, channels)));
  } finally {
    rmSync(profile, { recursive: true, force: true });
  }
}

function main(): void {
  const check = process.argv.includes('--check');
  const problems: string[] = [];
  mkdirSync(SVG_DIR, { recursive: true });
  const chrome = check ? '' : findChrome();
  for (const spec of ASSET_SPECS) {
    const svgPath = join(SVG_DIR, `${spec.name}.svg`);
    const pngPath = join(ASSET_DIR, `${spec.name}.png`);
    const svg = buildSvg(spec);
    if (check) {
      const committed = existsSync(svgPath) ? readFileSync(svgPath, 'utf8') : '';
      if (committed !== svg) problems.push(`${spec.name}.svg is out of date`);
    } else {
      writeFileSync(svgPath, svg);
      render(chrome, svgPath, pngPath, spec);
    }
    if (!existsSync(pngPath)) {
      problems.push(`${spec.name}.png is missing`);
      continue;
    }
    problems.push(...inspectPng(spec, decodePng(readFileSync(pngPath))));
  }
  if (problems.length > 0) {
    for (const problem of problems) console.error(`render-assets: ${problem}`);
    process.exit(1);
  }
  console.info(`render-assets: ${check ? 'verified' : 'rendered'} ${ASSET_SPECS.length} assets`);
}

if (import.meta.main) main();
