/**
 * Native widget sources derived from the shared packages (T-8.25; SCREEN_AND_FLOW_MAP §11). The
 * widget extension and the Glance receivers render without the JS runtime, so everything they
 * need is emitted as Swift / Kotlin / Android resources and committed:
 * - the design-token colours (`@da/design-tokens` `generated/native/*`, copied verbatim);
 * - the `widgets.*` messages of `@da/i18n` for both locales, with each ICU plural flattened into
 *   its `one` / `other` text (`#` becomes the `{arg}` slot the native formatter fills);
 * - the Turkish locative suffix of a time (`{time_loc}`: "07:30'da"), tabulated from the
 *   `@da/i18n` suffix rules by the number that is read last (the minutes, or the hour on the hour);
 * - the Android widget-picker names (`res/values{,-en}/da_widgets_strings.xml`).
 *
 * `node scripts/generate-widget-native.mjs` writes the files; `test/widget-native.test.ts` fails
 * when a committed file drifts from the packages. Only erasable TypeScript (Node type stripping).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { trCaseSuffix } from '../../../../../packages/i18n/src/tr-suffix.ts';

type Locale = 'tr' | 'en';

export interface FlatMessage {
  readonly one: string;
  readonly other: string;
  /** The argument that picks `one` / `other`, or null when the message has no plural. */
  readonly plural: string | null;
}

/** Output paths, relative to `apps/mobile`. */
export const WIDGET_NATIVE_FILES = {
  swiftColors: 'targets/widget/Generated/WidgetColors.swift',
  swiftStrings: 'targets/widget/Generated/WidgetStrings.swift',
  kotlinColors:
    'modules/da-widgets/android/src/main/java/expo/modules/dawidgets/generated/DaColors.kt',
  kotlinStrings:
    'modules/da-widgets/android/src/main/java/expo/modules/dawidgets/generated/DaStrings.kt',
  androidPickerTr: 'modules/da-widgets/android/src/main/res/values/da_widgets_strings.xml',
  androidPickerEn: 'modules/da-widgets/android/src/main/res/values-en/da_widgets_strings.xml',
} as const;

const HEADER =
  'Generated by apps/mobile/modules/da-widgets/plugin/generate-native.ts from @da/i18n and ' +
  '@da/design-tokens. Do not edit; run `pnpm --filter @da/mobile widgets:generate`.';

function flattenKeys(value: unknown, prefix: string, out: Map<string, string>): void {
  if (typeof value === 'string') {
    out.set(prefix, value);
    return;
  }
  if (typeof value !== 'object' || value === null) throw new Error(`bad catalog entry ${prefix}`);
  for (const [key, child] of Object.entries(value)) {
    flattenKeys(child, prefix === '' ? key : `${prefix}.${key}`, out);
  }
}

/** Reads the balanced `{…}` body that starts at `open` (the index of `{`); returns its end index. */
function balanced(message: string, open: number): number {
  let depth = 0;
  for (let i = open; i < message.length; i++) {
    if (message[i] === '{') depth++;
    else if (message[i] === '}') {
      depth--;
      if (depth === 0) return i;
    }
  }
  throw new Error(`unbalanced braces in "${message}"`);
}

/**
 * Flattens the ICU subset the widget messages use: plain `{arg}` placeholders and at most one
 * `{arg, plural, one {…} other {…}}`. Anything else (select, number skeletons, nested plurals)
 * is rejected so a catalog change cannot silently render raw ICU on a widget.
 */
export function flattenMessage(message: string): FlatMessage {
  const text = message.replaceAll("''", "'");
  const match = /\{(\w+), plural, /.exec(text);
  if (match === null) {
    if (/\{\w+,/.test(text)) throw new Error(`unsupported ICU syntax in "${message}"`);
    return { one: text, other: text, plural: null };
  }
  const arg = match[1] ?? '';
  const start = match.index;
  const end = balanced(text, start);
  const options = new Map<string, string>();
  let i = start + match[0].length;
  while (i < end) {
    const selector = /^\s*([=\w]+)\s*\{/.exec(text.slice(i, end));
    if (selector === null) break;
    const open = i + selector[0].length - 1;
    const close = balanced(text, open);
    options.set(selector[1] ?? '', text.slice(open + 1, close));
    i = close + 1;
  }
  const other = options.get('other');
  if (other === undefined) throw new Error(`plural without "other" in "${message}"`);
  const pick = (body: string) => body.replaceAll('#', `{${arg}}`);
  const before = text.slice(0, start);
  const after = text.slice(end + 1);
  if (/\{\w+,/.test(before + after)) throw new Error(`more than one plural in "${message}"`);
  return {
    one: before + pick(options.get('one') ?? other) + after,
    other: before + pick(other) + after,
    plural: arg,
  };
}

/** `widgets.*` of one locale, flattened and sorted by key. */
export function widgetMessages(appRoot: string, locale: Locale): [string, FlatMessage][] {
  const file = join(appRoot, '../../packages/i18n/messages', locale, 'widgets.json');
  const keys = new Map<string, string>();
  flattenKeys(JSON.parse(readFileSync(file, 'utf8')), '', keys);
  return [...keys.entries()]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([key, message]) => [key, flattenMessage(message)]);
}

/** Turkish locative suffixes: by the hour (full hours, 0–23) and by the minutes (1–59). */
export function trLocativeTables(): { byHour: string[]; byMinute: string[] } {
  const pad = (n: number) => String(n).padStart(2, '0');
  return {
    byHour: Array.from({ length: 24 }, (_, h) => trCaseSuffix(`${pad(h)}:00`, 'locative')),
    byMinute: Array.from({ length: 60 }, (_, m) =>
      m === 0 ? '' : trCaseSuffix(`00:${pad(m)}`, 'locative'),
    ),
  };
}

const swiftString = (value: string) => JSON.stringify(value);
const kotlinString = (value: string) => JSON.stringify(value).replaceAll('$', '\\$');

function swiftStrings(appRoot: string): string {
  const table = (locale: Locale) =>
    widgetMessages(appRoot, locale)
      .map(
        ([key, m]) =>
          `    ${swiftString(key)}: Entry(one: ${swiftString(m.one)}, other: ${swiftString(m.other)}, plural: ${m.plural === null ? 'nil' : swiftString(m.plural)}),`,
      )
      .join('\n');
  const { byHour, byMinute } = trLocativeTables();
  return `// ${HEADER}
import Foundation

/// The \`widgets.*\` messages of @da/i18n; the widget picks the table by the snapshot locale.
enum WidgetStrings {
  struct Entry {
    let one: String
    let other: String
    let plural: String?
  }

  static let tr: [String: Entry] = [
${table('tr')}
  ]

  static let en: [String: Entry] = [
${table('en')}
  ]

  /// Turkish locative suffix of a full hour ("07:00'de"), indexed by the hour.
  static let trLocativeByHour: [String] = [${byHour.map(swiftString).join(', ')}]

  /// Turkish locative suffix of a time by its minutes ("07:30'da"), indexed by the minute.
  static let trLocativeByMinute: [String] = [${byMinute.map(swiftString).join(', ')}]
}
`;
}

function kotlinStrings(appRoot: string): string {
  const table = (locale: Locale) =>
    widgetMessages(appRoot, locale)
      .map(
        ([key, m]) =>
          `        ${kotlinString(key)} to Entry(${kotlinString(m.one)}, ${kotlinString(m.other)}, ${m.plural === null ? 'null' : kotlinString(m.plural)}),`,
      )
      .join('\n');
  const { byHour, byMinute } = trLocativeTables();
  return `// ${HEADER}
package expo.modules.dawidgets.generated

/** The \`widgets.*\` messages of @da/i18n; the widget picks the table by the snapshot locale. */
object DaStrings {
    data class Entry(val one: String, val other: String, val plural: String?)

    val tr: Map<String, Entry> = mapOf(
${table('tr')}
    )

    val en: Map<String, Entry> = mapOf(
${table('en')}
    )

    /** Turkish locative suffix of a full hour ("07:00'de"), indexed by the hour. */
    val trLocativeByHour: List<String> = listOf(${byHour.map(kotlinString).join(', ')})

    /** Turkish locative suffix of a time by its minutes ("07:30'da"), indexed by the minute. */
    val trLocativeByMinute: List<String> = listOf(${byMinute.map(kotlinString).join(', ')})
}
`;
}

const PICKER_KEYS = {
  da_widget_next_name: 'gallery.nextName',
  da_widget_next_description: 'gallery.nextDescription',
  da_widget_today_name: 'gallery.todayName',
  da_widget_today_description: 'gallery.todayDescription',
} as const;

function xmlEscape(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll("'", "\\'")
    .replaceAll('"', '\\"');
}

function pickerStrings(appRoot: string, locale: Locale): string {
  const messages = new Map(widgetMessages(appRoot, locale));
  const rows = Object.entries(PICKER_KEYS).map(([name, key]) => {
    const message = messages.get(key);
    if (message === undefined) throw new Error(`widgets.${key} is missing (${locale})`);
    return `    <string name="${name}">${xmlEscape(message.other)}</string>`;
  });
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${HEADER} -->
<resources>
${rows.join('\n')}
</resources>
`;
}

/** Every generated file, keyed by its path relative to `apps/mobile`. */
export function generateWidgetNative(appRoot: string): Map<string, string> {
  const tokens = join(appRoot, '../../packages/design-tokens/generated/native');
  const files = new Map<string, string>();
  files.set(
    WIDGET_NATIVE_FILES.swiftColors,
    readFileSync(join(tokens, 'WidgetColors.swift'), 'utf8'),
  );
  files.set(WIDGET_NATIVE_FILES.kotlinColors, readFileSync(join(tokens, 'DaColors.kt'), 'utf8'));
  files.set(WIDGET_NATIVE_FILES.swiftStrings, swiftStrings(appRoot));
  files.set(WIDGET_NATIVE_FILES.kotlinStrings, kotlinStrings(appRoot));
  files.set(WIDGET_NATIVE_FILES.androidPickerTr, pickerStrings(appRoot, 'tr'));
  files.set(WIDGET_NATIVE_FILES.androidPickerEn, pickerStrings(appRoot, 'en'));
  return files;
}

export function writeWidgetNative(appRoot: string): string[] {
  const written: string[] = [];
  for (const [path, content] of generateWidgetNative(appRoot)) {
    const target = join(appRoot, path);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content);
    written.push(path);
  }
  return written;
}
