/**
 * Meeting routes (IMPLEMENTATION_PLAN T-5.10; API_CONTRACTS API-MEET-01 `POST /meetings/:eventId/
 * prep`, API-MEET-02 `…/notes`, API-MEET-03 `…/post`, API-MEET-04 `…/prep/audio`; M§21, M§22).
 * Pro (`meeting_prep` / `commitments`) is enforced by the route gate. Prep is generated by JOB-15
 * (R-23: precomputed at T-60 for external or VIP meetings, otherwise on tap); the client polls
 * `meeting_preps` through PostgREST (R-19). Post-meeting commitments become pending
 * `commitment_create` approvals ("Kaydet" approves them with `approved_via='in_place'`).
 */
import {
  MeetingNoteBody,
  MeetingPostBody,
  MeetingPrepAudioBody,
  MeetingPrepBody,
  routes,
} from '@da/validation';
import type { ApprovalPayload, ApprovalView } from '@da/validation';
import { currentUser } from '../../_shared/auth/user.ts';
import { AppError } from '../../_shared/errors.ts';
import type { AppContext, UserAuth } from '../../_shared/http/context.ts';
import { sendData } from '../../_shared/http/respond.ts';
import {
  mountRoute,
  parseJsonBody,
  validateRequest,
  validBody,
  validParams,
} from '../../_shared/http/validate.ts';
import { withIdempotency } from '../../_shared/idempotency.ts';
import { interactiveAiError, POLL_AFTER_MS } from '../../_shared/services/assist/common.ts';
import type { MeetingEventRow, MeetingNoteRow } from '../../_shared/services/assist/store.ts';
import { proposeApproval } from '../../_shared/services/approvals/propose.ts';
import { toApprovalView } from '../../_shared/services/approvals/view.ts';
import {
  briefingAudioKey,
  meetingAudioPath,
  NATIVE_FALLBACK_NOTICE,
  paragraphChapters,
  premiumTtsAvailable,
} from '../../_shared/services/briefings/audio.ts';
import { isOn } from '../../_shared/services/flags.ts';
import { extractPostMeeting } from '../../_shared/services/meetings/post.ts';
import {
  attendeesOf,
  loadPrepSources,
  PREP_FRESH_MS,
  prepView,
  summaryParagraphs,
} from '../../_shared/services/meetings/prep.ts';
import { SIGNED_AUDIO_TTL_S } from '../../_shared/services/storage.ts';
import type { RequestRepos, RouteKit, RouteRegistrar } from '../deps.ts';
import { serviceDeps } from './approvals.ts';
import { assistOf, requireQuota } from './assist-api.ts';

const WINDOW_BEFORE_MS = 2 * 3_600_000;
const WINDOW_AFTER_MS = 14 * 86_400_000;
const POST_WINDOW_MS = 48 * 3_600_000;

async function ownedEvent(
  kit: RouteKit,
  userId: string,
  eventId: string,
): Promise<MeetingEventRow> {
  const event = await assistOf(kit).assist.store.meetingEvent(userId, eventId);
  if (event === null) throw new AppError('NOT_FOUND', { details: { resource: 'calendar_event' } });
  return event;
}

async function requireMeetingFlag(kit: RouteKit, userId: string) {
  const user = await assistOf(kit).intel.ai.users.load(userId);
  if (!isOn(user.flags, 'feature.meeting_prep')) {
    throw new AppError('FEATURE_DISABLED', { details: { feature: 'meeting_prep' } });
  }
  return user;
}

/** API-MEET-01: fresh prep → 200; otherwise `generating` + JOB-15 → 202. */
async function prep(
  kit: RouteKit,
  auth: UserAuth,
  eventId: string,
  refresh: boolean,
  correlationId: string,
) {
  const { assist } = assistOf(kit);
  await requireMeetingFlag(kit, auth.userId);
  const event = await ownedEvent(kit, auth.userId, eventId);
  const now = kit.now();
  const start = Date.parse(event.start_at);
  if (
    event.status === 'cancelled' ||
    start < now.getTime() - WINDOW_BEFORE_MS ||
    start > now.getTime() + WINDOW_AFTER_MS
  ) {
    throw new AppError('NOT_FOUND', {
      details: { resource: 'calendar_event', reason: 'outside_prep_window' },
    });
  }
  const sources = await loadPrepSources(assist.store, auth.userId, event, now);
  const existing = await assist.store.meetingPrep(auth.userId, eventId);
  const fresh =
    existing?.status === 'ready' &&
    existing.source_hash === sources.hash &&
    existing.generated_at !== null &&
    now.getTime() - Date.parse(existing.generated_at) < PREP_FRESH_MS;
  if (
    existing !== null &&
    existing.status === 'ready' &&
    existing.source_hash === sources.hash &&
    (fresh || !refresh)
  ) {
    return { status: 200 as const, data: { prep: prepView(existing, event), job: null } };
  }
  if (existing?.status === 'generating') {
    const running = await kit.deps
      .repos(auth)
      .jobs.byKey(`meeting_prep:${eventId}:${existing.source_hash ?? sources.hash}`);
    if (running !== null && ['queued', 'running', 'retrying'].includes(running.status)) {
      return {
        status: 202 as const,
        data: {
          prep: prepView(existing, event),
          job: { job_id: running.id, status: running.status, poll_after_ms: POLL_AFTER_MS },
        },
      };
    }
  }
  await requireQuota(kit, auth, 'meeting_preps_daily');
  const row = await assist.store.upsertMeetingPrep({
    ...(existing ?? {
      user_id: auth.userId,
      calendar_event_id: eventId,
      purpose: null,
      purpose_evidence: [],
      primary_contact_id: null,
      last_interaction: null,
      recent_email_ids: [],
      open_loops: [],
      user_commitment_ids: [],
      their_commitment_ids: [],
      relevant_files: [],
      talking_points: [],
      summary_2min: null,
      reading_time_sec: null,
      sources: [],
      generated_at: null,
      prompt_version_id: null,
      ai_request_id: null,
    }),
    status: 'generating',
    source_hash: existing?.source_hash ?? null,
    source_provider: event.provider,
    source_timestamp: event.updated_at,
    confidence: 0.5,
  });
  // An unchanged source set regenerated after 30 min gets its own key per 30-minute bucket.
  const bucket =
    existing?.source_hash === sources.hash ? `:${Math.floor(now.getTime() / PREP_FRESH_MS)}` : '';
  const jobId = await kit.deps.repos(auth).jobs.enqueue({
    type: 'meeting_prep',
    idempotencyKey: `meeting_prep:${eventId}:${sources.hash}${bucket}`,
    payload: { user_id: auth.userId, calendar_event_id: eventId, trigger: 'user' },
    userId: auth.userId,
    priority: 20,
    maxAttempts: 4,
    correlationId,
  });
  return {
    status: 202 as const,
    data: {
      prep: prepView(row, event),
      job: { job_id: jobId, status: 'queued', poll_after_ms: POLL_AFTER_MS },
    },
  };
}

function noteView(note: MeetingNoteRow) {
  return {
    id: note.id,
    calendar_event_id: note.calendar_event_id,
    body: note.body,
    source: note.input === 'voice_transcript' ? 'voice' : 'text',
    created_at: new Date(note.created_at).toISOString(),
  };
}

type CommitmentPayload = Extract<ApprovalPayload, { action_type: 'commitment_create' }>;

function proposalOf(view: ApprovalView, payload: CommitmentPayload) {
  return {
    approval: view,
    text: payload.text,
    counterparty_label: payload.counterparty.name ?? payload.counterparty.email ?? '',
    due_at: payload.due_at,
    due_text: payload.due_text ?? null,
    direction: payload.direction,
    confidence: payload.confidence,
    quote: payload.evidence.quote,
  };
}

/** API-MEET-03 replay: the proposals of an existing post-meeting note. */
async function replayPost(
  c: AppContext,
  kit: RouteKit,
  repos: RequestRepos,
  auth: UserAuth,
  note: MeetingNoteRow,
) {
  const ids = await assistOf(kit).assist.store.approvalIdsByBatch(auth.userId, note.id);
  const deps = serviceDeps(c, kit, repos);
  const proposals = [];
  for (const id of ids) {
    const row = await repos.approvals.get(auth.userId, id);
    if (row === null || row.action_type !== 'commitment_create') continue;
    proposals.push(
      proposalOf(toApprovalView(row, { locale: deps.locale }), row.payload as CommitmentPayload),
    );
  }
  return { note_id: note.id, proposals, none_found: proposals.length === 0 };
}

async function post(
  c: AppContext,
  kit: RouteKit,
  auth: UserAuth,
  eventId: string,
  body: { client_post_id: string; text: string; source: 'text' | 'voice' },
) {
  const { assist, intel } = assistOf(kit);
  const repos = kit.deps.repos(auth);
  const event = await ownedEvent(kit, auth.userId, eventId);
  const replay = await assist.store.meetingNoteByClient(auth.userId, body.client_post_id);
  if (replay !== null) {
    if (replay.calendar_event_id !== eventId) throw new AppError('NOT_FOUND');
    return await replayPost(c, kit, repos, auth, replay);
  }
  const now = kit.now();
  const end = Date.parse(event.end_at);
  if (end > now.getTime() || end < now.getTime() - POST_WINDOW_MS) {
    throw new AppError('NOT_FOUND', {
      details: { resource: 'calendar_event', reason: 'outside_post_window' },
    });
  }
  const user = await intel.ai.users.load(auth.userId);
  const note = await assist.store.insertMeetingNote({
    user_id: auth.userId,
    calendar_event_id: eventId,
    kind: 'post_meeting',
    body: body.text,
    input: body.source === 'voice' ? 'voice_transcript' : 'text',
    client_note_id: body.client_post_id,
  });
  const attendees = attendeesOf(event);
  const contacts = await assist.store.contactsForEmails(
    auth.userId,
    attendees.map((a) => a.email),
  );
  const outcome = await extractPostMeeting(
    {
      runtime: intel.ai.runtime,
      user,
      correlationId: c.get('correlationId'),
      canary: intel.ai.canary,
    },
    { event, note, attendees, contacts, now },
  );
  if (outcome.kind !== 'ok') throw interactiveAiError(outcome.reason);
  const deps = serviceDeps(c, kit, repos);
  const proposals = [];
  for (const p of outcome.proposals) {
    const out = await proposeApproval(deps, {
      userId: auth.userId,
      payload: p.payload,
      origin: 'post_meeting',
      originRefId: note.id,
      batchId: note.id,
      actor: 'user',
    });
    proposals.push(proposalOf(out.view, p.payload));
  }
  return { note_id: note.id, proposals, none_found: proposals.length === 0 };
}

export const registerMeetingRoutes: RouteRegistrar = (app, kit) => {
  const idem = { repo: kit.deps.idempotency, now: () => kit.now().getTime() };

  const prepRoute = routes['POST /meetings/:eventId/prep'];
  mountRoute(
    app,
    prepRoute,
    ...kit.chain({ gate: true, rateLimit: 'api_default' }),
    parseJsonBody(prepRoute),
    validateRequest(prepRoute),
    (c) => {
      const auth = currentUser(c);
      const params = validParams(c, prepRoute.request.params);
      const body = validBody(c, MeetingPrepBody);
      let status: 200 | 202 = 200;
      return withIdempotency(c, idem, {
        // Read after `execute`: 200 for a fresh prep, 202 while JOB-15 generates.
        get status() {
          return status;
        },
        async execute() {
          const out = await prep(kit, auth, params.eventId, body.refresh, c.get('correlationId'));
          status = out.status;
          return {
            data: out.data,
            ref: { type: 'meeting_prep', id: out.data.prep.id },
            ...(status === 202 ? { meta: { poll_after_ms: POLL_AFTER_MS } } : {}),
          };
        },
        async replay() {
          const { assist } = assistOf(kit);
          const event = await ownedEvent(kit, auth.userId, params.eventId);
          const row = await assist.store.meetingPrep(auth.userId, params.eventId);
          if (row === null) throw new AppError('NOT_FOUND');
          return { prep: prepView(row, event), job: null };
        },
      });
    },
  );

  const notes = routes['POST /meetings/:eventId/notes'];
  mountRoute(
    app,
    notes,
    ...kit.chain({ gate: true, rateLimit: 'api_default' }),
    parseJsonBody(notes),
    validateRequest(notes),
    async (c) => {
      const auth = currentUser(c);
      const params = validParams(c, notes.request.params);
      const body = validBody(c, MeetingNoteBody);
      const { assist, intel } = assistOf(kit);
      await ownedEvent(kit, auth.userId, params.eventId);
      const existing = await assist.store.meetingNoteByClient(auth.userId, body.client_note_id);
      if (existing !== null) {
        if (existing.calendar_event_id !== params.eventId) throw new AppError('NOT_FOUND');
        c.header('Idempotency-Replayed', 'true');
        return sendData(c, noteView(existing), 201, { idempotency_replayed: true });
      }
      const note = await assist.store.insertMeetingNote({
        user_id: auth.userId,
        calendar_event_id: params.eventId,
        kind: 'prep_note',
        body: body.body,
        input: body.source === 'voice' ? 'voice_transcript' : 'text',
        client_note_id: body.client_note_id,
      });
      const user = await intel.ai.users.load(auth.userId);
      if (user.isPro) {
        await kit.deps.repos(auth).jobs.enqueue({
          type: 'embedding',
          idempotencyKey: `embedding:${auth.userId}:meeting_note:${note.id}`,
          payload: { user_id: auth.userId, items: [{ kind: 'meeting_note', id: note.id }] },
          userId: auth.userId,
          correlationId: c.get('correlationId'),
        });
      }
      return sendData(c, noteView(note), 201);
    },
  );

  const postRoute = routes['POST /meetings/:eventId/post'];
  mountRoute(
    app,
    postRoute,
    ...kit.chain({ gate: true, rateLimit: 'api_default' }),
    parseJsonBody(postRoute),
    validateRequest(postRoute),
    async (c) => {
      const auth = currentUser(c);
      const params = validParams(c, postRoute.request.params);
      const body = validBody(c, MeetingPostBody);
      const data = await post(c, kit, auth, params.eventId, body);
      return sendData(c, data, 201);
    },
  );

  const audio = routes['POST /meetings/:eventId/prep/audio'];
  mountRoute(
    app,
    audio,
    ...kit.chain({ gate: true, rateLimit: 'meeting_prep_audio' }),
    parseJsonBody(audio),
    validateRequest(audio),
    async (c) => {
      const auth = currentUser(c);
      const params = validParams(c, audio.request.params);
      const body = validBody(c, MeetingPrepAudioBody);
      const { assist, intel } = assistOf(kit);
      const user = await intel.ai.users.load(auth.userId);
      if (!isOn(user.flags, 'feature.voice')) {
        throw new AppError('FEATURE_DISABLED', { details: { feature: 'voice' } });
      }
      await ownedEvent(kit, auth.userId, params.eventId);
      const row = await assist.store.meetingPrep(auth.userId, params.eventId);
      if (row === null) throw new AppError('NOT_FOUND', { details: { resource: 'meeting_prep' } });
      if (row.status !== 'ready' || row.source_hash !== body.prep_version_hash) {
        throw new AppError('STATE_CONFLICT', { details: { reason: 'prep_changed' } });
      }
      const paragraphs = summaryParagraphs(row);
      const native = (notice: string | null, premium: 'generating' | 'unavailable' | null) => ({
        mode: 'native' as const,
        language: user.locale === 'en' ? 'en-US' : 'tr-TR',
        paragraphs,
        notice_key: notice,
        premium_status: premium,
      });
      const path = meetingAudioPath(auth.userId, row.id, body.prep_version_hash);
      const now = kit.now();
      if ((await assist.storage.stat('briefing-audio', path)) !== null) {
        const url = await assist.storage.signedUrl('briefing-audio', path, SIGNED_AUDIO_TTL_S);
        const chapters = paragraphChapters(paragraphs);
        return sendData(c, {
          mode: 'premium',
          signed_url: url,
          expires_at: new Date(now.getTime() + SIGNED_AUDIO_TTL_S * 1000).toISOString(),
          duration_s: chapters.reduce((n, ch) => n + ch.duration_s, 0),
          chapters: chapters.map(({ index, title, start_s }) => ({ index, title, start_s })),
        });
      }
      if (paragraphs.length > 0 && (await premiumTtsAvailable(intel.ai.runtime, user))) {
        await kit.deps.repos(auth).jobs.enqueue({
          type: 'briefing_audio',
          idempotencyKey: briefingAudioKey('meeting_prep', row.id, body.prep_version_hash),
          payload: {
            target: 'meeting_prep',
            id: row.id,
            version: body.prep_version_hash,
            user_id: auth.userId,
          },
          userId: auth.userId,
          maxAttempts: 3,
          correlationId: c.get('correlationId'),
        });
        return sendData(c, native(null, 'generating'), 202, { poll_after_ms: POLL_AFTER_MS });
      }
      return sendData(c, native(NATIVE_FALLBACK_NOTICE, 'unavailable'));
    },
  );
};
