-- Migration · referrals: codes, apply, evaluation context, decisions and capped rewards (T-7.03)
-- Spec: docs/API_CONTRACTS.md API-BIZ-01, API-BIZ-02, JOB-25; docs/DATABASE_AND_RLS_PLAN.md §4.6
-- (referral_codes, referrals, referral_credits), §4.8 (privacy_tombstones); plan §16.
--
-- The anti-abuse rules themselves live in packages/domain (referrals/risk.ts, qualify.ts,
-- evaluate.ts); these functions only gather hashed signals and apply decisions atomically. Raw
-- e-mails and Apple subjects leave the database only towards the Edge Function, which hashes them
-- with HASH_PEPPER and never stores or logs them.

set local lock_timeout = '10s';
set local statement_timeout = '10min';

-- ═══ Codes (API-BIZ-02) ══════════════════════════════════════════════════════════════════════
-- Returns the user's code, inserting p_candidate (generated by packages/domain
-- generateReferralCode) when the user has none. NULL means the candidate collided with another
-- user's code: the caller generates a new one and retries.
create function private.ensure_referral_code(p_user uuid, p_candidate text) returns text
  language plpgsql
  security definer
  set search_path = ''
  as $$
declare
  v_code text;
begin
  select rc.code into v_code from public.referral_codes rc where rc.user_id = p_user;
  if found then
    return v_code;
  end if;
  if p_candidate is null or not private.referral_code_valid(p_candidate) then
    raise exception 'VALIDATION_FAILED:code' using errcode = '22023';
  end if;
  begin
    insert into public.referral_codes (user_id, code) values (p_user, p_candidate);
    return p_candidate;
  exception when unique_violation then
    select rc.code into v_code from public.referral_codes rc where rc.user_id = p_user;
    return v_code;
  end;
end
$$;

-- API-BIZ-02: reward days, yearly cap and usage, earned days, the user's referrals (newest first,
-- referee shown only as an initial) and the user's own referral status.
create function private.referral_overview(p_user uuid, p_now timestamptz default now()) returns jsonb
  language sql stable
  security definer
  set search_path = ''
  as $$
    select jsonb_build_object(
      'code', (select rc.code from public.referral_codes rc where rc.user_id = p_user),
      'reward_days', private.app_setting_int('referral.reward_days', 14),
      'cap_per_year', coalesce(private.plan_limit_int(p_user, 'referral_rewards_per_year'), 6),
      'rewarded_this_year', (select count(*) from public.referral_credits c
                             where c.user_id = p_user and c.side = 'referrer' and c.created_at > p_now - interval '365 days'),
      'earned_days_total', (select coalesce(sum(c.days), 0) from public.referral_credits c where c.user_id = p_user),
      'referrals', coalesce((
        select jsonb_agg(jsonb_build_object('id', x.id, 'status', x.status, 'created_at', x.applied_at,
                                            'initial', x.initial) order by x.applied_at desc, x.id)
        from (select r.id, r.status, r.applied_at,
                     upper(left(coalesce(nullif(btrim(p.display_name), ''), split_part(u.email, '@', 1)), 1)) as initial
              from public.referrals r
              left join public.profiles p on p.user_id = r.referee_id
              left join auth.users u on u.id = r.referee_id
              where r.referrer_id = p_user
              order by r.applied_at desc, r.id
              limit 50) as x), '[]'::jsonb),
      'referred_by', (select jsonb_build_object('status', r.status) from public.referrals r where r.referee_id = p_user))
  $$;

-- ═══ Apply (API-BIZ-01) ══════════════════════════════════════════════════════════════════════
-- Everything checkReferralApply (packages/domain) needs: the active code's owner, both parties'
-- raw identity material (hashed by the caller), their stored installation hashes and the
-- referee's qualification progress.
create function private.referral_apply_context(p_referee uuid, p_code text, p_installation uuid default null)
  returns jsonb
  language sql stable
  security definer
  set search_path = ''
  as $$
    with owner as (
      select rc.user_id from public.referral_codes rc where rc.code = upper(p_code) and rc.disabled_at is null
    )
    select jsonb_build_object(
      'code_owner', (select o.user_id from owner o),
      'settings', coalesce((select jsonb_object_agg(s.key, s.value) from public.app_settings s where s.key like 'referral.%'),
                           '{}'::jsonb),
      'referee', (select jsonb_build_object(
          'user_id', u.id,
          'created_at', u.created_at,
          'email', u.email,
          'apple_sub', private.user_apple_sub(u.id),
          'has_referral', exists (select 1 from public.referrals r where r.referee_id = u.id),
          'device_hashes', coalesce((select jsonb_agg(distinct encode(i.device_hash, 'hex')) from public.app_installations i
                                     where i.user_id = u.id), '[]'::jsonb),
          'installation_device_hash', (select encode(i.device_hash, 'hex') from public.app_installations i
                                       where i.installation_id = p_installation and i.user_id = u.id),
          'onboarding_completed_at', (select p.onboarding_completed_at from public.profiles p where p.user_id = u.id),
          'account_connected_at', (select min(coalesce(a.connected_at, a.created_at)) from public.connected_accounts a
                                   where a.user_id = u.id and a.status = 'healthy'),
          'first_briefing_at', (select min(coalesce(b.delivered_at, b.updated_at)) from public.briefings b
                                where b.user_id = u.id and b.status = 'delivered'))
        from auth.users u where u.id = p_referee),
      'owner', (select jsonb_build_object(
          'user_id', u.id,
          'email', u.email,
          'apple_sub', private.user_apple_sub(u.id),
          'device_hashes', coalesce((select jsonb_agg(distinct encode(i.device_hash, 'hex')) from public.app_installations i
                                     where i.user_id = u.id), '[]'::jsonb))
        from owner o join auth.users u on u.id = o.user_id))
  $$;

-- Inserts the pending referral (one per referee), enqueues its first evaluation at
-- max(now, p_run_after) and audits user.referral.applied. A second referral for the same referee
-- raises REFERRAL_ALREADY_APPLIED (23505).
create function private.apply_referral(
  p_referee uuid, p_referrer uuid, p_code text, p_source text, p_device_hash bytea, p_email_hash bytea,
  p_signals jsonb, p_run_after timestamptz, p_correlation_id uuid default null
) returns jsonb
  language plpgsql
  security definer
  set search_path = ''
  as $$
declare
  v_id uuid;
  v_applied timestamptz;
begin
  if p_source not in ('deep_link', 'manual', 'install_referrer') then
    raise exception 'VALIDATION_FAILED:source' using errcode = '22023';
  end if;
  if not exists (select 1 from public.referral_codes rc
                 where rc.code = upper(p_code) and rc.user_id = p_referrer and rc.disabled_at is null) then
    raise exception 'REFERRAL_CODE_INVALID' using errcode = 'P0002';
  end if;
  insert into public.referrals (referrer_id, referee_id, code, status, referee_device_hash, referee_email_hash, risk_signals)
  values (p_referrer, p_referee, upper(p_code), 'pending', p_device_hash, p_email_hash,
          coalesce(p_signals, '{}'::jsonb) || jsonb_build_object('source', p_source))
  on conflict (referee_id) where referee_id is not null do nothing
  returning id, applied_at into v_id, v_applied;
  if v_id is null then
    raise exception 'REFERRAL_ALREADY_APPLIED' using errcode = '23505';
  end if;
  perform private.enqueue_job('referral_evaluate', 'referral_evaluate:' || v_id || ':apply',
                              jsonb_build_object('referral_id', v_id), p_referee, null,
                              greatest(now(), coalesce(p_run_after, now())), 100, 5, p_correlation_id);
  perform private.audit_log_append('user', p_referee, null, 'user.referral.applied', 'referral', v_id::text, p_referee,
                                   null, 'success', jsonb_build_object('source', p_source), p_correlation_id);
  return jsonb_build_object('referral_id', v_id, 'status', 'pending', 'applied_at', v_applied);
end
$$;

-- ═══ Evaluation (JOB-25) ═════════════════════════════════════════════════════════════════════
-- The inputs of assessReferralRisk / qualify / evaluateReferral for one referral: both parties'
-- identity material, the referrer's other referees (hashed signals only), the referral graph
-- reachable from the referee (loop detection), the referrer's applications around this one (velocity) and
-- referrer-side rewards (yearly cap), the number of other accounts sharing a device or a connected
-- mailbox with the referee, the referral.* settings and the referrer plan's yearly cap.
create function private.referral_evaluation_context(p_referral_id uuid, p_now timestamptz default now()) returns jsonb
  language plpgsql stable
  security definer
  set search_path = ''
  as $$
declare
  r public.referrals;
  v_siblings uuid[];
  v_referee_hashes bytea[];
  v_referee_mailboxes text[];
begin
  select * into r from public.referrals x where x.id = p_referral_id;
  if not found then
    raise exception 'NOT_FOUND' using errcode = 'P0002';
  end if;
  select coalesce(array_agg(x.referee_id), '{}') into v_siblings from public.referrals x
  where x.referrer_id = r.referrer_id and x.id <> r.id and x.status <> 'rejected' and x.referee_id is not null;
  select coalesce(array_agg(i.device_hash), '{}') into v_referee_hashes from public.app_installations i
  where i.user_id = r.referee_id;
  if r.referee_device_hash is not null then
    v_referee_hashes := v_referee_hashes || r.referee_device_hash;
  end if;
  select coalesce(array_agg(lower(a.account_email::text)), '{}') into v_referee_mailboxes from public.connected_accounts a
  where a.user_id = r.referee_id and a.account_email is not null and a.status <> 'disconnected';

  return jsonb_build_object(
    'referral', jsonb_build_object(
      'id', r.id, 'status', r.status, 'applied_at', r.applied_at, 'referrer_id', r.referrer_id,
      'referee_id', r.referee_id, 'referee_email_hash', encode(r.referee_email_hash, 'hex'),
      'referee_device_hash', encode(r.referee_device_hash, 'hex'), 'risk_signals', r.risk_signals),
    'referee', (select jsonb_build_object(
        'user_id', u.id, 'created_at', u.created_at, 'email', u.email, 'apple_sub', private.user_apple_sub(u.id),
        'installation_ids', coalesce((select jsonb_agg(i.installation_id order by i.created_at) from public.app_installations i
                                      where i.user_id = u.id), '[]'::jsonb),
        'device_hashes', coalesce((select jsonb_agg(distinct encode(h, 'hex')) from unnest(v_referee_hashes) as h), '[]'::jsonb),
        'provider_emails', to_jsonb(v_referee_mailboxes),
        'onboarding_completed_at', (select p.onboarding_completed_at from public.profiles p where p.user_id = u.id),
        'account_connected_at', (select min(coalesce(a.connected_at, a.created_at)) from public.connected_accounts a
                                 where a.user_id = u.id and a.status = 'healthy'),
        'first_briefing_at', (select min(coalesce(b.delivered_at, b.updated_at)) from public.briefings b
                              where b.user_id = u.id and b.status = 'delivered'))
      from auth.users u where u.id = r.referee_id),
    'referrer', (select jsonb_build_object(
        'user_id', u.id, 'email', u.email, 'apple_sub', private.user_apple_sub(u.id),
        'device_hashes', coalesce((select jsonb_agg(distinct encode(i.device_hash, 'hex')) from public.app_installations i
                                   where i.user_id = u.id), '[]'::jsonb),
        'provider_emails', coalesce((select jsonb_agg(distinct lower(a.account_email::text)) from public.connected_accounts a
                                     where a.user_id = u.id and a.account_email is not null and a.status <> 'disconnected'),
                                    '[]'::jsonb))
      from auth.users u where u.id = r.referrer_id),
    'siblings', coalesce((select jsonb_agg(jsonb_build_object(
        'user_id', x.referee_id, 'email_hash', encode(x.referee_email_hash, 'hex'),
        'device_hash', encode(x.referee_device_hash, 'hex')))
      from public.referrals x where x.referee_id = any(v_siblings) and x.referrer_id = r.referrer_id), '[]'::jsonb),
    'edges', coalesce((
      with recursive walk (referrer_id, referee_id, depth) as (
        select x.referrer_id, x.referee_id, 1 from public.referrals x
        where x.referrer_id = r.referee_id and x.status <> 'rejected' and x.referee_id is not null
        union
        select x.referrer_id, x.referee_id, w.depth + 1 from public.referrals x
        join walk w on x.referrer_id = w.referee_id
        where x.status <> 'rejected' and x.referee_id is not null and w.depth < 20
      )
      select jsonb_agg(distinct jsonb_build_object('referrer_id', w.referrer_id, 'referee_id', w.referee_id))
      from (select * from walk limit 1000) as w), '[]'::jsonb),
    'referrer_applied_at', coalesce((select jsonb_agg(x.applied_at order by x.applied_at) from public.referrals x
                                     where x.referrer_id = r.referrer_id
                                       and x.applied_at between r.applied_at - interval '1 day' and r.applied_at + interval '1 day'),
                                    '[]'::jsonb),
    'referrer_rewarded_at', coalesce((select jsonb_agg(c.created_at order by c.created_at) from public.referral_credits c
                                      where c.user_id = r.referrer_id and c.side = 'referrer'
                                        and c.created_at > p_now - interval '365 days'), '[]'::jsonb),
    'other_accounts_sharing', (
      select count(distinct z.user_id) from (
        select i.user_id from public.app_installations i where i.device_hash = any(v_referee_hashes)
        union
        select a.user_id from public.connected_accounts a
        where lower(a.account_email::text) = any(v_referee_mailboxes) and a.status <> 'disconnected'
      ) as z
      where z.user_id is distinct from r.referee_id and z.user_id is distinct from r.referrer_id
        and not (z.user_id = any(v_siblings))),
    'settings', coalesce((select jsonb_object_agg(s.key, s.value) from public.app_settings s where s.key like 'referral.%'),
                         '{}'::jsonb),
    'rewards_per_year', coalesce(private.plan_limit_int(r.referrer_id, 'referral_rewards_per_year'), 6));
end
$$;

-- True when any referee signal hash (kind + hex hash) is a live privacy tombstone (UT-REF-08).
create function private.referral_tombstone_match(p_signals jsonb) returns boolean
  language sql stable
  security definer
  set search_path = ''
  as $$
    select exists (
      select 1 from public.privacy_tombstones t
      join jsonb_to_recordset(coalesce(p_signals, '[]'::jsonb)) as s (kind text, hash text)
        on t.kind = s.kind and t.signal_hash = decode(s.hash, 'hex')
      where t.expires_at > now())
  $$;

-- Rewards a qualified referral honouring the referrer's yearly cap (JOB-25 step 3): below the cap
-- both sides are rewarded by private.reward_referral; at the cap (or when the referrer account is
-- gone) only the referee is credited and granted, the referral becomes `rewarded` and
-- risk_signals.referrer_withheld records why. Idempotent: credits are unique per (referral, side)
-- and grants per key referral:{id}:{side}.
create function private.reward_referral_with_cap(p_referral_id uuid) returns jsonb
  language plpgsql
  security definer
  set search_path = ''
  as $$
declare
  r public.referrals;
  v_days smallint := private.app_setting_int('referral.reward_days', 14)::smallint;
  v_cap integer;
  v_used integer;
  v_credit uuid;
  v_grant public.entitlement_grants;
  v_result jsonb;
begin
  select * into r from public.referrals x where x.id = p_referral_id for update;
  if not found then
    raise exception 'NOT_FOUND' using errcode = 'P0002';
  end if;
  if r.status = 'rewarded' then
    return jsonb_build_object('status', 'rewarded', 'replayed', true, 'days', v_days,
                              'sides', coalesce((select jsonb_agg(c.side order by c.side) from public.referral_credits c
                                                 where c.referral_id = r.id), '[]'::jsonb));
  end if;
  if r.status <> 'qualified' then
    raise exception 'ILLEGAL_TRANSITION:%->rewarded', r.status using errcode = '55000';
  end if;
  if r.referrer_id is not null then
    v_cap := coalesce(private.plan_limit_int(r.referrer_id, 'referral_rewards_per_year'), 6);
    select count(*) into v_used from public.referral_credits c
    where c.user_id = r.referrer_id and c.side = 'referrer' and c.created_at > now() - interval '365 days';
    if v_used < v_cap then
      v_result := private.reward_referral(r.id);
      return v_result || jsonb_build_object(
        'days', v_days,
        'sides', coalesce((select jsonb_agg(c.side order by c.side) from public.referral_credits c
                           where c.referral_id = r.id), '[]'::jsonb));
    end if;
  end if;
  if r.referee_id is null then
    raise exception 'STATE_CONFLICT:referee_deleted' using errcode = '55000';
  end if;

  insert into public.referral_credits (referral_id, user_id, side, days, idempotency_key)
  values (r.id, r.referee_id, 'referee', v_days, 'referral:' || r.id || ':referee')
  on conflict (referral_id, side) do nothing
  returning id into v_credit;
  if v_credit is null then
    select c.id into v_credit from public.referral_credits c where c.referral_id = r.id and c.side = 'referee';
  end if;
  v_grant := private.grant_entitlement(r.referee_id, 'referral_referee', v_days, null, null,
                                       'referral:' || r.id || ':referee', v_credit);
  update public.referral_credits c set entitlement_grant_id = v_grant.id where c.id = v_credit and c.entitlement_grant_id is null;
  update public.referrals x
  set status = 'rewarded', rewarded_at = now(),
      risk_signals = x.risk_signals || jsonb_build_object('referrer_withheld',
                                                          case when r.referrer_id is null then 'referrer_deleted' else 'cap_reached' end)
  where x.id = r.id;
  perform private.audit_log_append('system', null, null, 'system.referral.rewarded', 'referral', r.id::text, r.referee_id,
                                   null, 'success',
                                   jsonb_build_object('days', v_days, 'referrer_withheld',
                                                      case when r.referrer_id is null then 'referrer_deleted' else 'cap_reached' end),
                                   null);
  return jsonb_build_object('status', 'rewarded', 'days', v_days, 'sides', jsonb_build_array('referee'),
                            'referee', jsonb_build_object('credit_id', v_credit, 'grant_id', v_grant.id),
                            'referrer_withheld', case when r.referrer_id is null then 'referrer_deleted' else 'cap_reached' end);
end
$$;

-- Applies one evaluateReferral decision under the row lock: wait (qualification and assessment
-- recorded), reject, flag (admin review, audit system.referral.flagged) or qualify (then the capped
-- reward in the same transaction). Only a pending referral changes; a qualified one (admin approval
-- in ADM-12) is rewarded; any other status is returned unchanged.
create function private.referral_decide(
  p_referral_id uuid, p_decision text, p_reject_reason text default null, p_risk_score integer default 0,
  p_assessment jsonb default '{}'::jsonb, p_qualification jsonb default null, p_correlation_id uuid default null
) returns jsonb
  language plpgsql
  security definer
  set search_path = ''
  as $$
declare
  r public.referrals;
  v_score smallint := least(greatest(coalesce(p_risk_score, 0), 0), 100)::smallint;
begin
  if p_decision not in ('wait', 'reject', 'flag', 'qualify') then
    raise exception 'VALIDATION_FAILED:decision' using errcode = '22023';
  end if;
  select * into r from public.referrals x where x.id = p_referral_id for update;
  if not found then
    raise exception 'NOT_FOUND' using errcode = 'P0002';
  end if;
  if r.status in ('qualified', 'rewarded') and p_decision = 'qualify' then
    return private.reward_referral_with_cap(r.id) || jsonb_build_object('referrer_id', r.referrer_id,
                                                                         'referee_id', r.referee_id);
  end if;
  if r.status <> 'pending' then
    return jsonb_build_object('status', r.status, 'changed', false);
  end if;

  update public.referrals x
  set risk_score = v_score,
      risk_signals = x.risk_signals || jsonb_build_object('assessment', coalesce(p_assessment, '{}'::jsonb)),
      qualification = coalesce(p_qualification, x.qualification),
      status = case p_decision when 'reject' then 'rejected'::public.referral_status
                               when 'flag' then 'flagged'::public.referral_status
                               when 'qualify' then 'qualified'::public.referral_status
                               else x.status end,
      rejected_at = case when p_decision = 'reject' then now() else x.rejected_at end,
      reject_reason = case when p_decision = 'reject' then p_reject_reason else x.reject_reason end,
      qualified_at = case when p_decision = 'qualify' then now() else x.qualified_at end
  where x.id = r.id;

  if p_decision = 'reject' then
    perform private.audit_log_append('system', null, null, 'system.referral.rejected', 'referral', r.id::text, r.referrer_id,
                                     null, 'success', jsonb_build_object('reason', p_reject_reason, 'risk_score', v_score),
                                     p_correlation_id);
    return jsonb_build_object('status', 'rejected', 'changed', true, 'reject_reason', p_reject_reason);
  elsif p_decision = 'flag' then
    perform private.audit_log_append('system', null, null, 'system.referral.flagged', 'referral', r.id::text, r.referrer_id,
                                     null, 'success', jsonb_build_object('risk_score', v_score,
                                                                         'flag_reasons', coalesce(p_assessment -> 'flag_reasons', '[]'::jsonb)),
                                     p_correlation_id);
    return jsonb_build_object('status', 'flagged', 'changed', true);
  elsif p_decision = 'wait' then
    return jsonb_build_object('status', 'pending', 'changed', false);
  end if;
  return private.reward_referral_with_cap(r.id) || jsonb_build_object('referrer_id', r.referrer_id,
                                                                       'referee_id', r.referee_id, 'changed', true);
end
$$;

revoke execute on function
  private.ensure_referral_code(uuid, text),
  private.referral_overview(uuid, timestamptz),
  private.referral_apply_context(uuid, text, uuid),
  private.apply_referral(uuid, uuid, text, text, bytea, bytea, jsonb, timestamptz, uuid),
  private.referral_evaluation_context(uuid, timestamptz),
  private.referral_tombstone_match(jsonb),
  private.reward_referral_with_cap(uuid),
  private.referral_decide(uuid, text, text, integer, jsonb, jsonb, uuid)
  from public;
grant execute on function
  private.ensure_referral_code(uuid, text),
  private.referral_overview(uuid, timestamptz),
  private.referral_apply_context(uuid, text, uuid),
  private.apply_referral(uuid, uuid, text, text, bytea, bytea, jsonb, timestamptz, uuid),
  private.referral_evaluation_context(uuid, timestamptz),
  private.referral_tombstone_match(jsonb),
  private.reward_referral_with_cap(uuid),
  private.referral_decide(uuid, text, text, integer, jsonb, jsonb, uuid)
  to service_role;

-- ═══ Service-role wrappers ═══════════════════════════════════════════════════════════════════
create function public.ensure_referral_code(p_user uuid, p_candidate text) returns text
  language sql
  security definer
  set search_path = ''
  as $$ select private.ensure_referral_code(p_user, p_candidate) $$;

create function public.referral_overview(p_user uuid, p_now timestamptz default now()) returns jsonb
  language sql stable
  security definer
  set search_path = ''
  as $$ select private.referral_overview(p_user, p_now) $$;

create function public.referral_apply_context(p_referee uuid, p_code text, p_installation uuid default null)
  returns jsonb
  language sql stable
  security definer
  set search_path = ''
  as $$ select private.referral_apply_context(p_referee, p_code, p_installation) $$;

create function public.apply_referral(
  p_referee uuid, p_referrer uuid, p_code text, p_source text, p_device_hash bytea, p_email_hash bytea,
  p_signals jsonb, p_run_after timestamptz, p_correlation_id uuid default null
) returns jsonb
  language sql
  security definer
  set search_path = ''
  as $$
    select private.apply_referral(p_referee, p_referrer, p_code, p_source, p_device_hash, p_email_hash, p_signals,
                                  p_run_after, p_correlation_id)
  $$;

create function public.referral_evaluation_context(p_referral_id uuid, p_now timestamptz default now()) returns jsonb
  language sql stable
  security definer
  set search_path = ''
  as $$ select private.referral_evaluation_context(p_referral_id, p_now) $$;

create function public.referral_tombstone_match(p_signals jsonb) returns boolean
  language sql stable
  security definer
  set search_path = ''
  as $$ select private.referral_tombstone_match(p_signals) $$;

create function public.referral_decide(
  p_referral_id uuid, p_decision text, p_reject_reason text default null, p_risk_score integer default 0,
  p_assessment jsonb default '{}'::jsonb, p_qualification jsonb default null, p_correlation_id uuid default null
) returns jsonb
  language sql
  security definer
  set search_path = ''
  as $$
    select private.referral_decide(p_referral_id, p_decision, p_reject_reason, p_risk_score, p_assessment,
                                   p_qualification, p_correlation_id)
  $$;

revoke execute on function
  public.ensure_referral_code(uuid, text),
  public.referral_overview(uuid, timestamptz),
  public.referral_apply_context(uuid, text, uuid),
  public.apply_referral(uuid, uuid, text, text, bytea, bytea, jsonb, timestamptz, uuid),
  public.referral_evaluation_context(uuid, timestamptz),
  public.referral_tombstone_match(jsonb),
  public.referral_decide(uuid, text, text, integer, jsonb, jsonb, uuid)
  from public, anon, authenticated;
grant execute on function
  public.ensure_referral_code(uuid, text),
  public.referral_overview(uuid, timestamptz),
  public.referral_apply_context(uuid, text, uuid),
  public.apply_referral(uuid, uuid, text, text, bytea, bytea, jsonb, timestamptz, uuid),
  public.referral_evaluation_context(uuid, timestamptz),
  public.referral_tombstone_match(jsonb),
  public.referral_decide(uuid, text, text, integer, jsonb, jsonb, uuid)
  to service_role;
